# This are used by /hack/update-codegen.sh
required = [
  "k8s.io/code-generator/cmd/defaulter-gen",
  "k8s.io/code-generator/cmd/deepcopy-gen",
  "k8s.io/code-generator/cmd/conversion-gen",
  "k8s.io/code-generator/cmd/client-gen",
  "k8s.io/code-generator/cmd/lister-gen",
  "k8s.io/code-generator/cmd/informer-gen",
  "k8s.io/code-generator/cmd/openapi-gen",
]

[prune]
  non-go = true
  unused-packages = true
  go-tests = true

# Prevent dep from pruning build scripts and codegen templates
[[prune.project]]
  name = "k8s.io/code-generator"
  non-go = false
  go-tests = false
  unused-packages = false

[[constraint]]
  name = "k8s.io/client-go"
  version = "=v9.0.0"

[[constraint]]
  name = "k8s.io/code-generator"
  version = "kubernetes-1.12.0"

[[constraint]]
  name = "k8s.io/apiextensions-apiserver"
  version = "kubernetes-1.12.0"

[[constraint]]
  name = "k8s.io/kubernetes"
  version = "=v1.12.0"

# Kube specific overrides
[[override]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.12.0"
[[override]]
  name = "k8s.io/api"
  version = "kubernetes-1.12.0"
[[override]]
  name = "k8s.io/gengo"
  revision = "ff07baa94012248e1ff712d34c3673bea92cd788"
# END Kube specific overrides

[[override]]
  name = "github.com/docker/docker"
  branch = "master"
[[constraint]]
  name = "github.com/vulcand/vulcand"
  branch = "master"
[[constraint]]
  name = "github.com/vulcand/route"
  branch = "master"
[[constraint]]
  name = "github.com/fsouza/go-dockerclient"
  branch = "master"
[[override]]
  name = "github.com/gorilla/mux"
  version = "v1.7.0"
[[override]]
  name = "golang.org/x/crypto"
  branch = "master"
[[constraint]]
  name = "github.com/nu7hatch/gouuid"
  revision = "179d4d0c4d8d407a32af483c2354df1d2c91e6c3"
[[constraint]]
  name = "github.com/aws/aws-sdk-go"
  version = "v1.16.21"
[[constraint]]
  name = "github.com/docker/machine"
  source = "github.com/cezarsa/machine"
  branch = "azureupdate"
[[constraint]]
  name = "github.com/digitalocean/godo"
  revision = "dfa802149cae7e4b8eb8bdd7cbbf619dab60bea4"
[[constraint]]
  name = "github.com/tsuru/gandalf"
  branch = "master"
[[constraint]]
  name = "golang.org/x/oauth2"
  revision = "a6bd8cefa1811bd24b86f8902872e4e8225f74c4"
[[constraint]]
  name = "gopkg.in/yaml.v2"
  revision = "53feefa2559fb8dfa8d81baad31be332c97d6c77"
[[constraint]]
  name = "github.com/sajari/fuzzy"
  revision = "bbbcac964e38148a7b43491a83d83b6b584600dc"
[[constraint]]
  name = "github.com/ajg/form"
  revision = "523a5da1a92f01b01f840b61689c0340a0243532"
[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.0"
[[constraint]]
  name = "github.com/diego-araujo/go-saml"
  revision = "81203d2425377605c5688e55dca1340b614b618d"
[[constraint]]
  name = "github.com/mattn/go-shellwords"
  revision = "005a0944d84452842197c2108bd9168ced206f78"
[[constraint]]
  name = "github.com/codegangsta/negroni"
  revision = "a13766a8c2572caeb14341b7de158aff2fd00fa9"
[[constraint]]
  name = "github.com/andrestc/docker-machine-driver-cloudstack"
  version = "v0.7.0"
[[constraint]]
  name = "github.com/hashicorp/go-version"
  revision = "0181db47023708a38c2d20d2fe25a5fa034d5743"
[[constraint]]
  name = "github.com/google/gops"
  branch = "master"
[[constraint]]
  name = "github.com/rancher/kontainer-engine"
  source = "github.com/cezarsa/kontainer-engine"
  branch = "noclientid"
[[override]]
  name = "github.com/rancher/rke"
  branch = "master"

# Misc overrides (transitive deps from docker, docker/machine, ...)
[[override]]
  name = "github.com/kardianos/osext"
  revision = "10da29423eb9a6269092eebdc2be32209612d9d2"
[[override]]
  name = "github.com/Azure/azure-sdk-for-go"
  version = "=v19.1.1"
[[override]]
  name = "github.com/Azure/go-autorest"
  version = "=v10.11.1"
[[override]]
  name = "github.com/prometheus/client_model"
  revision = "fa8ad6fec33561be4280a8f0514318c79d7f6cb6"
[[override]]
  name = "github.com/Microsoft/go-winio"
  revision = "d8f60f2dd117cd64c2825143a89ecb6f158ad743"
[[override]]
  name = "github.com/gorilla/pat"
  revision = "ae2e162c4b2ae96aa66b596b2c18f17834299ed0"
[[override]]
  name = "github.com/xanzy/go-cloudstack"
  branch = "master"
[[override]]
  name = "github.com/vulcand/predicate"
  revision = "cb0bff91a7ab7cf7571e661ff883fc997bc554a3"
[[override]]
  name = "github.com/pyr/egoscale"
  revision = "ab4b0d7ff424c462da486aef27f354cdeb29a319"
[[override]]
  name = "github.com/dgrijalva/jwt-go"
  revision = "01aeca54ebda6e0fbfafd0a524d234159c05ec20"
[[override]]
  name = "github.com/docker/spdystream"
  revision = "449fdfce4d962303d702fec724ef0ad181c92528"
[[override]]
  name = "github.com/emicklei/go-restful"
  revision = "ff4f55a206334ef123e4f79bbf348980da81ca46"
[[override]]
  name = "github.com/gogo/protobuf"
  revision = "c0656edd0d9eab7c66d1eb0c568f9039345796f7"
[[override]]
  name = "github.com/RobotsAndPencils/go-saml"
  revision = "aa127de49a0111329d9dbd2e19ddf21da90eb931"
[[override]]
  name = "github.com/howeyc/fsnotify"
  revision = "5102fde921d31f59c6e45d835aa01f0213aade0f"
[[override]]
  name = "github.com/ugorji/go"
  revision = "v1.1.1"
[[override]]
  name = "github.com/google/go-querystring"
  revision = "547ef5ac979778feb2f760cdb5f4eae1a2207b86"
[[override]]
  name = "github.com/bradfitz/go-smtpd"
  revision = "5b56f4f917c7f54e3822b9c64df54da596b63c1d"
[[override]]
  name = "github.com/golang/glog"
  revision = "23def4e6c14b4da8ac2ed8007337bc5eb5007998"
[[override]]
  name = "github.com/docker/go-units"
  revision = "5d2041e26a699eaca682e2ea41c8f891e1060444"
[[override]]
  name = "github.com/gorilla/context"
  revision = "708054d61e5a2918b9f4e9700000ee611dcf03f5"
[[override]]
  name = "github.com/mitchellh/mapstructure"
  revision = "ca63d7c062ee3c9f34db231e352b60012b4fd0c1"
[[override]]
  name = "github.com/tent/http-link-go"
  revision = "ac974c61c2f990f4115b119354b5e0b47550e888"
[[override]]
  name = "github.com/prometheus/common"
  revision = "0d5de9d6d8629cb8bee6d4674da4127cd8b615a3"
[[override]]
  name = "github.com/vmware/govcloudair"
  version = "v0.0.2"
[[override]]
  name = "github.com/cenkalti/backoff"
  revision = "8edc80b07f38c27352fb186d971c628a6c32552b"
[[override]]
  name = "github.com/googleapis/gnostic"
  revision = "68f4ded48ba9414dab2ae69b3f0d69971da73aa5"
[[override]]
  name = "github.com/hashicorp/golang-lru"
  revision = "a0d98a5f288019575c6d1f4bb1573fef2d1fcdc4"
[[override]]
  name = "github.com/howeyc/gopass"
  revision = "bf9dde6d0d2c004a008c27aaee91170c786f6db8"
[[override]]
  name = "github.com/juju/ratelimit"
  revision = "5b9ff866471762aa2ab2dced63c9fb6f53921342"
[[override]]
  name = "github.com/samalba/dockerclient"
  revision = "a3036261847103270e9f732509f43b5f98710ace"
[[override]]
  name = "github.com/vmware/govmomi"
  revision = "b932baf416e9101c762b7075f12af5a6fb364627"
[[override]]
  name = "github.com/prometheus/procfs"
  revision = "abf152e5f3e97f2fafac028d2cc06c1feb87ffa5"
[[override]]
  name = "github.com/matttproud/golang_protobuf_extensions"
  revision = "c12348ce28de40eed0136aa2b644d0ee0650e56c"
[[override]]
  name = "github.com/opencontainers/runc"
  revision = "419d5be191c18eff75a3d0b2a16e20c7a9eb71db"
[[override]]
  name = "github.com/beorn7/perks"
  revision = "4c0e84591b9aa9e6dcfdf3e020114cd81f89d5f9"
[[override]]
  name = "github.com/docker/go-connections"
  revision = "v0.4.0"
[[override]]
  name = "github.com/rackspace/gophercloud"
  revision = "c90cb954266e1bdd6d1914678fd6909fc5fabbfa"
[[override]]
  name = "github.com/hashicorp/go-cleanhttp"
  revision = "ad28ea4487f05916463e2423a55166280e8254b5"
[[override]]
  name = "gopkg.in/inf.v0"
  version = "v0.9.0"
[[override]]
  name = "github.com/golang/protobuf"
  branch = "master"

[[constraint]]
  name = "github.com/globalsign/mgo"
  version = "r2018.06.15"
