// Code generated by go-swagger; DO NOT EDIT.

package app

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewAppCreateParams creates a new AppCreateParams object
// with the default values initialized.
func NewAppCreateParams() *AppCreateParams {

	return &AppCreateParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewAppCreateParamsWithTimeout creates a new AppCreateParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewAppCreateParamsWithTimeout(timeout time.Duration) *AppCreateParams {

	return &AppCreateParams{

		timeout: timeout,
	}
}

// NewAppCreateParamsWithContext creates a new AppCreateParams object
// with the default values initialized, and the ability to set a context for a request
func NewAppCreateParamsWithContext(ctx context.Context) *AppCreateParams {

	return &AppCreateParams{

		Context: ctx,
	}
}

// NewAppCreateParamsWithHTTPClient creates a new AppCreateParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewAppCreateParamsWithHTTPClient(client *http.Client) *AppCreateParams {

	return &AppCreateParams{
		HTTPClient: client,
	}
}

/*AppCreateParams contains all the parameters to send to the API endpoint
for the app create operation typically these are written to a http.Request
*/
type AppCreateParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the app create params
func (o *AppCreateParams) WithTimeout(timeout time.Duration) *AppCreateParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the app create params
func (o *AppCreateParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the app create params
func (o *AppCreateParams) WithContext(ctx context.Context) *AppCreateParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the app create params
func (o *AppCreateParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the app create params
func (o *AppCreateParams) WithHTTPClient(client *http.Client) *AppCreateParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the app create params
func (o *AppCreateParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *AppCreateParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
