// Code generated by go-swagger; DO NOT EDIT.

package app

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewAppShellParams creates a new AppShellParams object
// with the default values initialized.
func NewAppShellParams() *AppShellParams {
	var ()
	return &AppShellParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewAppShellParamsWithTimeout creates a new AppShellParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewAppShellParamsWithTimeout(timeout time.Duration) *AppShellParams {
	var ()
	return &AppShellParams{

		timeout: timeout,
	}
}

// NewAppShellParamsWithContext creates a new AppShellParams object
// with the default values initialized, and the ability to set a context for a request
func NewAppShellParamsWithContext(ctx context.Context) *AppShellParams {
	var ()
	return &AppShellParams{

		Context: ctx,
	}
}

// NewAppShellParamsWithHTTPClient creates a new AppShellParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewAppShellParamsWithHTTPClient(client *http.Client) *AppShellParams {
	var ()
	return &AppShellParams{
		HTTPClient: client,
	}
}

/*AppShellParams contains all the parameters to send to the API endpoint
for the app shell operation typically these are written to a http.Request
*/
type AppShellParams struct {

	/*App
	  App name.

	*/
	App string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the app shell params
func (o *AppShellParams) WithTimeout(timeout time.Duration) *AppShellParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the app shell params
func (o *AppShellParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the app shell params
func (o *AppShellParams) WithContext(ctx context.Context) *AppShellParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the app shell params
func (o *AppShellParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the app shell params
func (o *AppShellParams) WithHTTPClient(client *http.Client) *AppShellParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the app shell params
func (o *AppShellParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithApp adds the app to the app shell params
func (o *AppShellParams) WithApp(app string) *AppShellParams {
	o.SetApp(app)
	return o
}

// SetApp adds the app to the app shell params
func (o *AppShellParams) SetApp(app string) {
	o.App = app
}

// WriteToRequest writes these params to a swagger request
func (o *AppShellParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param app
	if err := r.SetPathParam("app", o.App); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
