// Code generated by go-swagger; DO NOT EDIT.

package app

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// AppShellReader is a Reader for the AppShell structure.
type AppShellReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *AppShellReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 101:
		result := NewAppShellSwitchingProtocols()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewAppShellSwitchingProtocols creates a AppShellSwitchingProtocols with default headers values
func NewAppShellSwitchingProtocols() *AppShellSwitchingProtocols {
	return &AppShellSwitchingProtocols{}
}

/*AppShellSwitchingProtocols handles this case with default header values.

Switch Protocol to websocket
*/
type AppShellSwitchingProtocols struct {
}

func (o *AppShellSwitchingProtocols) Error() string {
	return fmt.Sprintf("[GET /apps/{app}/shell][%d] appShellSwitchingProtocols ", 101)
}

func (o *AppShellSwitchingProtocols) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
