// Code generated by go-swagger; DO NOT EDIT.

package app

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// PostAppsReader is a Reader for the PostApps structure.
type PostAppsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostAppsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 201:
		result := NewPostAppsCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewPostAppsBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 401:
		result := NewPostAppsUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 403:
		result := NewPostAppsForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 409:
		result := NewPostAppsConflict()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPostAppsCreated creates a PostAppsCreated with default headers values
func NewPostAppsCreated() *PostAppsCreated {
	return &PostAppsCreated{}
}

/*PostAppsCreated handles this case with default header values.

App created
*/
type PostAppsCreated struct {
}

func (o *PostAppsCreated) Error() string {
	return fmt.Sprintf("[POST /apps][%d] postAppsCreated ", 201)
}

func (o *PostAppsCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPostAppsBadRequest creates a PostAppsBadRequest with default headers values
func NewPostAppsBadRequest() *PostAppsBadRequest {
	return &PostAppsBadRequest{}
}

/*PostAppsBadRequest handles this case with default header values.

Invalid data
*/
type PostAppsBadRequest struct {
}

func (o *PostAppsBadRequest) Error() string {
	return fmt.Sprintf("[POST /apps][%d] postAppsBadRequest ", 400)
}

func (o *PostAppsBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPostAppsUnauthorized creates a PostAppsUnauthorized with default headers values
func NewPostAppsUnauthorized() *PostAppsUnauthorized {
	return &PostAppsUnauthorized{}
}

/*PostAppsUnauthorized handles this case with default header values.

Unauthorized
*/
type PostAppsUnauthorized struct {
}

func (o *PostAppsUnauthorized) Error() string {
	return fmt.Sprintf("[POST /apps][%d] postAppsUnauthorized ", 401)
}

func (o *PostAppsUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPostAppsForbidden creates a PostAppsForbidden with default headers values
func NewPostAppsForbidden() *PostAppsForbidden {
	return &PostAppsForbidden{}
}

/*PostAppsForbidden handles this case with default header values.

Quota exceeded
*/
type PostAppsForbidden struct {
}

func (o *PostAppsForbidden) Error() string {
	return fmt.Sprintf("[POST /apps][%d] postAppsForbidden ", 403)
}

func (o *PostAppsForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPostAppsConflict creates a PostAppsConflict with default headers values
func NewPostAppsConflict() *PostAppsConflict {
	return &PostAppsConflict{}
}

/*PostAppsConflict handles this case with default header values.

App already exists
*/
type PostAppsConflict struct {
}

func (o *PostAppsConflict) Error() string {
	return fmt.Sprintf("[POST /apps][%d] postAppsConflict ", 409)
}

func (o *PostAppsConflict) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
