package app

import (
	"fmt"
	"github.com/timeredbull/tsuru/config"
	"github.com/timeredbull/tsuru/fs"
	"github.com/timeredbull/tsuru/log"
	"io"
	"io/ioutil"
	"launchpad.net/goyaml"
	"os"
	"path"
	"syscall"
	"time"
)

const (
	ChanSize    = 10
	runAttempts = 5
)

type message struct {
	app     *App
	success chan bool
}

var env chan message = make(chan message, ChanSize)

var environConfPath = path.Join(os.ExpandEnv("${HOME}"), ".juju", "environments.yaml")

type cmd struct {
	cmd    string
	result chan cmdResult
	u      Unit
}

type cmdResult struct {
	err    error
	output []byte
}

var cmds chan cmd = make(chan cmd)

func init() {
	go collectEnvVars()
	go runCommands()
}

func runCommands() {
	for cmd := range cmds {
		out, err := cmd.u.Command(cmd.cmd)
		if cmd.result != nil {
			r := cmdResult{output: out, err: err}
			cmd.result <- r
		}
	}
}

func runCmd(command string, msg message) {
	c := cmd{
		u:      *msg.app.unit(),
		cmd:    command,
		result: make(chan cmdResult),
	}
	cmds <- c
	var r cmdResult
	r = <-c.result
	for i := 0; r.err != nil && i < runAttempts; i++ {
		cmds <- c
		r = <-c.result
	}
	log.Printf("running %s on %s, output:\n %s", command, msg.app.Name, string(r.output))
	if msg.success != nil {
		msg.success <- r.err == nil
	}
}

func collectEnvVars() {
	for e := range env {
		cmd := "cat > /home/application/apprc <<END\n"
		cmd += fmt.Sprintf("# generated by tsuru at %s\n", time.Now().Format(time.RFC822Z))
		for k, v := range e.app.Env {
			cmd += fmt.Sprintf(`export %s="%s"`+"\n", k, v.Value)
		}
		cmd += "END\n"
		runCmd(cmd, e)
	}
}

type jujuEnv struct {
	AccessKey     string `yaml:"access-key"`
	SecretKey     string `yaml:"secret-key"`
	Ec2           string `yaml:"ec2-uri"`
	S3            string `yaml:"s3-uri"`
	JujuOrigin    string `yaml:"juju-origin"`
	Type          string `yaml:"type"`
	AdminSecret   string `yaml:"admin-secret"`
	ControlBucket string `yaml:"control-bucket"`
	Series        string `yaml:"default-series"`
	ImageId       string `yaml:"default-image-id"`
	InstanceType  string `yaml:"default-instance-type"`
}

func newJujuEnv(access, secret string) (jujuEnv, error) {
	ec2, err := config.GetString("juju:ec2")
	if err != nil {
		return jujuEnv{}, err
	}
	s3, err := config.GetString("juju:s3")
	if err != nil {
		return jujuEnv{}, err
	}
	jujuOrigin, err := config.GetString("juju:origin")
	if err != nil {
		return jujuEnv{}, err
	}
	series, err := config.GetString("juju:series")
	if err != nil {
		return jujuEnv{}, err
	}
	imageId, err := config.GetString("juju:image-id")
	if err != nil {
		return jujuEnv{}, err
	}
	instaceType, err := config.GetString("juju:instance-type")
	if err != nil {
		return jujuEnv{}, err
	}
	adminSecret, err := newUUID()
	if err != nil {
		return jujuEnv{}, err
	}
	controlBucket := fmt.Sprintf("juju-%s", adminSecret)
	return jujuEnv{
		Ec2:           ec2,
		S3:            s3,
		JujuOrigin:    jujuOrigin,
		Type:          "ec2",
		AdminSecret:   adminSecret,
		ControlBucket: controlBucket,
		Series:        series,
		ImageId:       imageId,
		InstanceType:  instaceType,
		AccessKey:     access,
		SecretKey:     secret,
	}, nil
}

func newEnviron(a *App) error {
	envs := map[string]map[string]jujuEnv{}
	file, err := filesystem().OpenFile(environConfPath, syscall.O_CREAT|syscall.O_RDWR, 0600)
	if err != nil {
		return err
	}
	defer file.Close()
	content, err := ioutil.ReadAll(file)
	if err != nil {
		return err
	}
	err = goyaml.Unmarshal(content, &envs)
	if err != nil {
		return err
	}
	if _, ok := envs["environments"]; !ok {
		envs["environments"] = map[string]jujuEnv{}
	}
	jujuEnv, err := newJujuEnv(a.KeystoneEnv.AccessKey, a.KeystoneEnv.secretKey)
	if err != nil {
		return err
	}
	envs["environments"][a.Name] = jujuEnv
	data, err := goyaml.Marshal(&envs)
	ret, err := file.Seek(0, 0)
	if err != nil {
		return err
	}
	if ret != 0 {
		return fmt.Errorf("Unexpected error when creating juju environment for app %s.", a.Name)
	}
	n, err := file.Write(data)
	if err != nil {
		return err
	}
	if n != len(data) {
		return io.ErrShortWrite
	}
	return nil
}

// removeEnviron removes a environ from environment.yaml
func removeEnviron(a *App) error {
	file, err := filesystem().OpenFile(environConfPath, syscall.O_RDWR, 0600)
	if err != nil {
		return err
	}
	defer file.Close()
	content, err := ioutil.ReadAll(file)
	if err != nil {
		return err
	}
	envs := map[string]map[string]jujuEnv{}
	err = goyaml.Unmarshal(content, &envs)
	delete(envs["environments"], a.Name)
	data, err := goyaml.Marshal(&envs)
	if err != nil {
		return err
	}
	n, err := file.Write(data)
	if err != nil {
		return err
	}
	if n != len(data) {
		return io.ErrShortWrite
	}
	return nil
}

var fsystem fs.Fs

func filesystem() fs.Fs {
	if fsystem == nil {
		fsystem = fs.OsFs{}
	}
	return fsystem
}
