// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// DeleteServicesNameInstancesInstanceReader is a Reader for the DeleteServicesNameInstancesInstance structure.
type DeleteServicesNameInstancesInstanceReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteServicesNameInstancesInstanceReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewDeleteServicesNameInstancesInstanceOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewDeleteServicesNameInstancesInstanceBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 401:
		result := NewDeleteServicesNameInstancesInstanceUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 404:
		result := NewDeleteServicesNameInstancesInstanceNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewDeleteServicesNameInstancesInstanceOK creates a DeleteServicesNameInstancesInstanceOK with default headers values
func NewDeleteServicesNameInstancesInstanceOK() *DeleteServicesNameInstancesInstanceOK {
	return &DeleteServicesNameInstancesInstanceOK{}
}

/*DeleteServicesNameInstancesInstanceOK handles this case with default header values.

Service removed
*/
type DeleteServicesNameInstancesInstanceOK struct {
}

func (o *DeleteServicesNameInstancesInstanceOK) Error() string {
	return fmt.Sprintf("[DELETE /services/{name}/instances/{instance}][%d] deleteServicesNameInstancesInstanceOK ", 200)
}

func (o *DeleteServicesNameInstancesInstanceOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteServicesNameInstancesInstanceBadRequest creates a DeleteServicesNameInstancesInstanceBadRequest with default headers values
func NewDeleteServicesNameInstancesInstanceBadRequest() *DeleteServicesNameInstancesInstanceBadRequest {
	return &DeleteServicesNameInstancesInstanceBadRequest{}
}

/*DeleteServicesNameInstancesInstanceBadRequest handles this case with default header values.

Bad request
*/
type DeleteServicesNameInstancesInstanceBadRequest struct {
}

func (o *DeleteServicesNameInstancesInstanceBadRequest) Error() string {
	return fmt.Sprintf("[DELETE /services/{name}/instances/{instance}][%d] deleteServicesNameInstancesInstanceBadRequest ", 400)
}

func (o *DeleteServicesNameInstancesInstanceBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteServicesNameInstancesInstanceUnauthorized creates a DeleteServicesNameInstancesInstanceUnauthorized with default headers values
func NewDeleteServicesNameInstancesInstanceUnauthorized() *DeleteServicesNameInstancesInstanceUnauthorized {
	return &DeleteServicesNameInstancesInstanceUnauthorized{}
}

/*DeleteServicesNameInstancesInstanceUnauthorized handles this case with default header values.

Unauthorized
*/
type DeleteServicesNameInstancesInstanceUnauthorized struct {
}

func (o *DeleteServicesNameInstancesInstanceUnauthorized) Error() string {
	return fmt.Sprintf("[DELETE /services/{name}/instances/{instance}][%d] deleteServicesNameInstancesInstanceUnauthorized ", 401)
}

func (o *DeleteServicesNameInstancesInstanceUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteServicesNameInstancesInstanceNotFound creates a DeleteServicesNameInstancesInstanceNotFound with default headers values
func NewDeleteServicesNameInstancesInstanceNotFound() *DeleteServicesNameInstancesInstanceNotFound {
	return &DeleteServicesNameInstancesInstanceNotFound{}
}

/*DeleteServicesNameInstancesInstanceNotFound handles this case with default header values.

Service instance not found
*/
type DeleteServicesNameInstancesInstanceNotFound struct {
}

func (o *DeleteServicesNameInstancesInstanceNotFound) Error() string {
	return fmt.Sprintf("[DELETE /services/{name}/instances/{instance}][%d] deleteServicesNameInstancesInstanceNotFound ", 404)
}

func (o *DeleteServicesNameInstancesInstanceNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
