// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewDeleteAppAppRoutersRouterParams creates a new DeleteAppAppRoutersRouterParams object
// with the default values initialized.
func NewDeleteAppAppRoutersRouterParams() *DeleteAppAppRoutersRouterParams {
	var ()
	return &DeleteAppAppRoutersRouterParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteAppAppRoutersRouterParamsWithTimeout creates a new DeleteAppAppRoutersRouterParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeleteAppAppRoutersRouterParamsWithTimeout(timeout time.Duration) *DeleteAppAppRoutersRouterParams {
	var ()
	return &DeleteAppAppRoutersRouterParams{

		timeout: timeout,
	}
}

// NewDeleteAppAppRoutersRouterParamsWithContext creates a new DeleteAppAppRoutersRouterParams object
// with the default values initialized, and the ability to set a context for a request
func NewDeleteAppAppRoutersRouterParamsWithContext(ctx context.Context) *DeleteAppAppRoutersRouterParams {
	var ()
	return &DeleteAppAppRoutersRouterParams{

		Context: ctx,
	}
}

// NewDeleteAppAppRoutersRouterParamsWithHTTPClient creates a new DeleteAppAppRoutersRouterParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDeleteAppAppRoutersRouterParamsWithHTTPClient(client *http.Client) *DeleteAppAppRoutersRouterParams {
	var ()
	return &DeleteAppAppRoutersRouterParams{
		HTTPClient: client,
	}
}

/*DeleteAppAppRoutersRouterParams contains all the parameters to send to the API endpoint
for the delete app app routers router operation typically these are written to a http.Request
*/
type DeleteAppAppRoutersRouterParams struct {

	/*App
	  App name.

	*/
	App string
	/*Router
	  Router name.

	*/
	Router string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the delete app app routers router params
func (o *DeleteAppAppRoutersRouterParams) WithTimeout(timeout time.Duration) *DeleteAppAppRoutersRouterParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete app app routers router params
func (o *DeleteAppAppRoutersRouterParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete app app routers router params
func (o *DeleteAppAppRoutersRouterParams) WithContext(ctx context.Context) *DeleteAppAppRoutersRouterParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete app app routers router params
func (o *DeleteAppAppRoutersRouterParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete app app routers router params
func (o *DeleteAppAppRoutersRouterParams) WithHTTPClient(client *http.Client) *DeleteAppAppRoutersRouterParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete app app routers router params
func (o *DeleteAppAppRoutersRouterParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithApp adds the app to the delete app app routers router params
func (o *DeleteAppAppRoutersRouterParams) WithApp(app string) *DeleteAppAppRoutersRouterParams {
	o.SetApp(app)
	return o
}

// SetApp adds the app to the delete app app routers router params
func (o *DeleteAppAppRoutersRouterParams) SetApp(app string) {
	o.App = app
}

// WithRouter adds the router to the delete app app routers router params
func (o *DeleteAppAppRoutersRouterParams) WithRouter(router string) *DeleteAppAppRoutersRouterParams {
	o.SetRouter(router)
	return o
}

// SetRouter adds the router to the delete app app routers router params
func (o *DeleteAppAppRoutersRouterParams) SetRouter(router string) {
	o.Router = router
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteAppAppRoutersRouterParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param app
	if err := r.SetPathParam("app", o.App); err != nil {
		return err
	}

	// path param router
	if err := r.SetPathParam("router", o.Router); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
