// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewDeletePlansPlanParams creates a new DeletePlansPlanParams object
// with the default values initialized.
func NewDeletePlansPlanParams() *DeletePlansPlanParams {
	var ()
	return &DeletePlansPlanParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeletePlansPlanParamsWithTimeout creates a new DeletePlansPlanParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeletePlansPlanParamsWithTimeout(timeout time.Duration) *DeletePlansPlanParams {
	var ()
	return &DeletePlansPlanParams{

		timeout: timeout,
	}
}

// NewDeletePlansPlanParamsWithContext creates a new DeletePlansPlanParams object
// with the default values initialized, and the ability to set a context for a request
func NewDeletePlansPlanParamsWithContext(ctx context.Context) *DeletePlansPlanParams {
	var ()
	return &DeletePlansPlanParams{

		Context: ctx,
	}
}

// NewDeletePlansPlanParamsWithHTTPClient creates a new DeletePlansPlanParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDeletePlansPlanParamsWithHTTPClient(client *http.Client) *DeletePlansPlanParams {
	var ()
	return &DeletePlansPlanParams{
		HTTPClient: client,
	}
}

/*DeletePlansPlanParams contains all the parameters to send to the API endpoint
for the delete plans plan operation typically these are written to a http.Request
*/
type DeletePlansPlanParams struct {

	/*Plan
	  Plan name.

	*/
	Plan string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the delete plans plan params
func (o *DeletePlansPlanParams) WithTimeout(timeout time.Duration) *DeletePlansPlanParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete plans plan params
func (o *DeletePlansPlanParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete plans plan params
func (o *DeletePlansPlanParams) WithContext(ctx context.Context) *DeletePlansPlanParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete plans plan params
func (o *DeletePlansPlanParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete plans plan params
func (o *DeletePlansPlanParams) WithHTTPClient(client *http.Client) *DeletePlansPlanParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete plans plan params
func (o *DeletePlansPlanParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithPlan adds the plan to the delete plans plan params
func (o *DeletePlansPlanParams) WithPlan(plan string) *DeletePlansPlanParams {
	o.SetPlan(plan)
	return o
}

// SetPlan adds the plan to the delete plans plan params
func (o *DeletePlansPlanParams) SetPlan(plan string) {
	o.Plan = plan
}

// WriteToRequest writes these params to a swagger request
func (o *DeletePlansPlanParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param plan
	if err := r.SetPathParam("plan", o.Plan); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
