// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// DeleteAppsAppUnitsReader is a Reader for the DeleteAppsAppUnits structure.
type DeleteAppsAppUnitsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteAppsAppUnitsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewDeleteAppsAppUnitsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewDeleteAppsAppUnitsBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 401:
		result := NewDeleteAppsAppUnitsUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 404:
		result := NewDeleteAppsAppUnitsNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewDeleteAppsAppUnitsOK creates a DeleteAppsAppUnitsOK with default headers values
func NewDeleteAppsAppUnitsOK() *DeleteAppsAppUnitsOK {
	return &DeleteAppsAppUnitsOK{}
}

/*DeleteAppsAppUnitsOK handles this case with default header values.

Units removed
*/
type DeleteAppsAppUnitsOK struct {
}

func (o *DeleteAppsAppUnitsOK) Error() string {
	return fmt.Sprintf("[DELETE /apps/{app}/units][%d] deleteAppsAppUnitsOK ", 200)
}

func (o *DeleteAppsAppUnitsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteAppsAppUnitsBadRequest creates a DeleteAppsAppUnitsBadRequest with default headers values
func NewDeleteAppsAppUnitsBadRequest() *DeleteAppsAppUnitsBadRequest {
	return &DeleteAppsAppUnitsBadRequest{}
}

/*DeleteAppsAppUnitsBadRequest handles this case with default header values.

Invalid data
*/
type DeleteAppsAppUnitsBadRequest struct {
}

func (o *DeleteAppsAppUnitsBadRequest) Error() string {
	return fmt.Sprintf("[DELETE /apps/{app}/units][%d] deleteAppsAppUnitsBadRequest ", 400)
}

func (o *DeleteAppsAppUnitsBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteAppsAppUnitsUnauthorized creates a DeleteAppsAppUnitsUnauthorized with default headers values
func NewDeleteAppsAppUnitsUnauthorized() *DeleteAppsAppUnitsUnauthorized {
	return &DeleteAppsAppUnitsUnauthorized{}
}

/*DeleteAppsAppUnitsUnauthorized handles this case with default header values.

Unauthorized
*/
type DeleteAppsAppUnitsUnauthorized struct {
}

func (o *DeleteAppsAppUnitsUnauthorized) Error() string {
	return fmt.Sprintf("[DELETE /apps/{app}/units][%d] deleteAppsAppUnitsUnauthorized ", 401)
}

func (o *DeleteAppsAppUnitsUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteAppsAppUnitsNotFound creates a DeleteAppsAppUnitsNotFound with default headers values
func NewDeleteAppsAppUnitsNotFound() *DeleteAppsAppUnitsNotFound {
	return &DeleteAppsAppUnitsNotFound{}
}

/*DeleteAppsAppUnitsNotFound handles this case with default header values.

App not found
*/
type DeleteAppsAppUnitsNotFound struct {
}

func (o *DeleteAppsAppUnitsNotFound) Error() string {
	return fmt.Sprintf("[DELETE /apps/{app}/units][%d] deleteAppsAppUnitsNotFound ", 404)
}

func (o *DeleteAppsAppUnitsNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
