// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// DeleteProvisionerNodeAddressReader is a Reader for the DeleteProvisionerNodeAddress structure.
type DeleteProvisionerNodeAddressReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteProvisionerNodeAddressReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewDeleteProvisionerNodeAddressOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 401:
		result := NewDeleteProvisionerNodeAddressUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 404:
		result := NewDeleteProvisionerNodeAddressNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewDeleteProvisionerNodeAddressOK creates a DeleteProvisionerNodeAddressOK with default headers values
func NewDeleteProvisionerNodeAddressOK() *DeleteProvisionerNodeAddressOK {
	return &DeleteProvisionerNodeAddressOK{}
}

/*DeleteProvisionerNodeAddressOK handles this case with default header values.

Ok
*/
type DeleteProvisionerNodeAddressOK struct {
}

func (o *DeleteProvisionerNodeAddressOK) Error() string {
	return fmt.Sprintf("[DELETE /{provisioner}/node/{address}][%d] deleteProvisionerNodeAddressOK ", 200)
}

func (o *DeleteProvisionerNodeAddressOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteProvisionerNodeAddressUnauthorized creates a DeleteProvisionerNodeAddressUnauthorized with default headers values
func NewDeleteProvisionerNodeAddressUnauthorized() *DeleteProvisionerNodeAddressUnauthorized {
	return &DeleteProvisionerNodeAddressUnauthorized{}
}

/*DeleteProvisionerNodeAddressUnauthorized handles this case with default header values.

Unauthorized
*/
type DeleteProvisionerNodeAddressUnauthorized struct {
}

func (o *DeleteProvisionerNodeAddressUnauthorized) Error() string {
	return fmt.Sprintf("[DELETE /{provisioner}/node/{address}][%d] deleteProvisionerNodeAddressUnauthorized ", 401)
}

func (o *DeleteProvisionerNodeAddressUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteProvisionerNodeAddressNotFound creates a DeleteProvisionerNodeAddressNotFound with default headers values
func NewDeleteProvisionerNodeAddressNotFound() *DeleteProvisionerNodeAddressNotFound {
	return &DeleteProvisionerNodeAddressNotFound{}
}

/*DeleteProvisionerNodeAddressNotFound handles this case with default header values.

Not found
*/
type DeleteProvisionerNodeAddressNotFound struct {
}

func (o *DeleteProvisionerNodeAddressNotFound) Error() string {
	return fmt.Sprintf("[DELETE /{provisioner}/node/{address}][%d] deleteProvisionerNodeAddressNotFound ", 404)
}

func (o *DeleteProvisionerNodeAddressNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
