// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// DeleteRolesRoleUserEmailReader is a Reader for the DeleteRolesRoleUserEmail structure.
type DeleteRolesRoleUserEmailReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteRolesRoleUserEmailReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewDeleteRolesRoleUserEmailOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewDeleteRolesRoleUserEmailBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 401:
		result := NewDeleteRolesRoleUserEmailUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 404:
		result := NewDeleteRolesRoleUserEmailNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewDeleteRolesRoleUserEmailOK creates a DeleteRolesRoleUserEmailOK with default headers values
func NewDeleteRolesRoleUserEmailOK() *DeleteRolesRoleUserEmailOK {
	return &DeleteRolesRoleUserEmailOK{}
}

/*DeleteRolesRoleUserEmailOK handles this case with default header values.

Ok
*/
type DeleteRolesRoleUserEmailOK struct {
}

func (o *DeleteRolesRoleUserEmailOK) Error() string {
	return fmt.Sprintf("[DELETE /roles/{role}/user/{email}][%d] deleteRolesRoleUserEmailOK ", 200)
}

func (o *DeleteRolesRoleUserEmailOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteRolesRoleUserEmailBadRequest creates a DeleteRolesRoleUserEmailBadRequest with default headers values
func NewDeleteRolesRoleUserEmailBadRequest() *DeleteRolesRoleUserEmailBadRequest {
	return &DeleteRolesRoleUserEmailBadRequest{}
}

/*DeleteRolesRoleUserEmailBadRequest handles this case with default header values.

Invalid data
*/
type DeleteRolesRoleUserEmailBadRequest struct {
}

func (o *DeleteRolesRoleUserEmailBadRequest) Error() string {
	return fmt.Sprintf("[DELETE /roles/{role}/user/{email}][%d] deleteRolesRoleUserEmailBadRequest ", 400)
}

func (o *DeleteRolesRoleUserEmailBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteRolesRoleUserEmailUnauthorized creates a DeleteRolesRoleUserEmailUnauthorized with default headers values
func NewDeleteRolesRoleUserEmailUnauthorized() *DeleteRolesRoleUserEmailUnauthorized {
	return &DeleteRolesRoleUserEmailUnauthorized{}
}

/*DeleteRolesRoleUserEmailUnauthorized handles this case with default header values.

Unauthorized
*/
type DeleteRolesRoleUserEmailUnauthorized struct {
}

func (o *DeleteRolesRoleUserEmailUnauthorized) Error() string {
	return fmt.Sprintf("[DELETE /roles/{role}/user/{email}][%d] deleteRolesRoleUserEmailUnauthorized ", 401)
}

func (o *DeleteRolesRoleUserEmailUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteRolesRoleUserEmailNotFound creates a DeleteRolesRoleUserEmailNotFound with default headers values
func NewDeleteRolesRoleUserEmailNotFound() *DeleteRolesRoleUserEmailNotFound {
	return &DeleteRolesRoleUserEmailNotFound{}
}

/*DeleteRolesRoleUserEmailNotFound handles this case with default header values.

Role not found
*/
type DeleteRolesRoleUserEmailNotFound struct {
}

func (o *DeleteRolesRoleUserEmailNotFound) Error() string {
	return fmt.Sprintf("[DELETE /roles/{role}/user/{email}][%d] deleteRolesRoleUserEmailNotFound ", 404)
}

func (o *DeleteRolesRoleUserEmailNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
