// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// DeletePlatformsPlatformReader is a Reader for the DeletePlatformsPlatform structure.
type DeletePlatformsPlatformReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeletePlatformsPlatformReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewDeletePlatformsPlatformOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 401:
		result := NewDeletePlatformsPlatformUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 404:
		result := NewDeletePlatformsPlatformNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewDeletePlatformsPlatformOK creates a DeletePlatformsPlatformOK with default headers values
func NewDeletePlatformsPlatformOK() *DeletePlatformsPlatformOK {
	return &DeletePlatformsPlatformOK{}
}

/*DeletePlatformsPlatformOK handles this case with default header values.

Platform removed
*/
type DeletePlatformsPlatformOK struct {
}

func (o *DeletePlatformsPlatformOK) Error() string {
	return fmt.Sprintf("[DELETE /platforms/{platform}][%d] deletePlatformsPlatformOK ", 200)
}

func (o *DeletePlatformsPlatformOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeletePlatformsPlatformUnauthorized creates a DeletePlatformsPlatformUnauthorized with default headers values
func NewDeletePlatformsPlatformUnauthorized() *DeletePlatformsPlatformUnauthorized {
	return &DeletePlatformsPlatformUnauthorized{}
}

/*DeletePlatformsPlatformUnauthorized handles this case with default header values.

Unauthorized
*/
type DeletePlatformsPlatformUnauthorized struct {
}

func (o *DeletePlatformsPlatformUnauthorized) Error() string {
	return fmt.Sprintf("[DELETE /platforms/{platform}][%d] deletePlatformsPlatformUnauthorized ", 401)
}

func (o *DeletePlatformsPlatformUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeletePlatformsPlatformNotFound creates a DeletePlatformsPlatformNotFound with default headers values
func NewDeletePlatformsPlatformNotFound() *DeletePlatformsPlatformNotFound {
	return &DeletePlatformsPlatformNotFound{}
}

/*DeletePlatformsPlatformNotFound handles this case with default header values.

Not found
*/
type DeletePlatformsPlatformNotFound struct {
}

func (o *DeletePlatformsPlatformNotFound) Error() string {
	return fmt.Sprintf("[DELETE /platforms/{platform}][%d] deletePlatformsPlatformNotFound ", 404)
}

func (o *DeletePlatformsPlatformNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
