// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// DeleteDockerNodecontainersNodecontainerReader is a Reader for the DeleteDockerNodecontainersNodecontainer structure.
type DeleteDockerNodecontainersNodecontainerReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteDockerNodecontainersNodecontainerReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewDeleteDockerNodecontainersNodecontainerOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 401:
		result := NewDeleteDockerNodecontainersNodecontainerUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 404:
		result := NewDeleteDockerNodecontainersNodecontainerNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewDeleteDockerNodecontainersNodecontainerOK creates a DeleteDockerNodecontainersNodecontainerOK with default headers values
func NewDeleteDockerNodecontainersNodecontainerOK() *DeleteDockerNodecontainersNodecontainerOK {
	return &DeleteDockerNodecontainersNodecontainerOK{}
}

/*DeleteDockerNodecontainersNodecontainerOK handles this case with default header values.

Ok
*/
type DeleteDockerNodecontainersNodecontainerOK struct {
}

func (o *DeleteDockerNodecontainersNodecontainerOK) Error() string {
	return fmt.Sprintf("[DELETE /docker/nodecontainers/{nodecontainer}][%d] deleteDockerNodecontainersNodecontainerOK ", 200)
}

func (o *DeleteDockerNodecontainersNodecontainerOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteDockerNodecontainersNodecontainerUnauthorized creates a DeleteDockerNodecontainersNodecontainerUnauthorized with default headers values
func NewDeleteDockerNodecontainersNodecontainerUnauthorized() *DeleteDockerNodecontainersNodecontainerUnauthorized {
	return &DeleteDockerNodecontainersNodecontainerUnauthorized{}
}

/*DeleteDockerNodecontainersNodecontainerUnauthorized handles this case with default header values.

Unauthorized
*/
type DeleteDockerNodecontainersNodecontainerUnauthorized struct {
}

func (o *DeleteDockerNodecontainersNodecontainerUnauthorized) Error() string {
	return fmt.Sprintf("[DELETE /docker/nodecontainers/{nodecontainer}][%d] deleteDockerNodecontainersNodecontainerUnauthorized ", 401)
}

func (o *DeleteDockerNodecontainersNodecontainerUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteDockerNodecontainersNodecontainerNotFound creates a DeleteDockerNodecontainersNodecontainerNotFound with default headers values
func NewDeleteDockerNodecontainersNodecontainerNotFound() *DeleteDockerNodecontainersNodecontainerNotFound {
	return &DeleteDockerNodecontainersNodecontainerNotFound{}
}

/*DeleteDockerNodecontainersNodecontainerNotFound handles this case with default header values.

Not found
*/
type DeleteDockerNodecontainersNodecontainerNotFound struct {
}

func (o *DeleteDockerNodecontainersNodecontainerNotFound) Error() string {
	return fmt.Sprintf("[DELETE /docker/nodecontainers/{nodecontainer}][%d] deleteDockerNodecontainersNodecontainerNotFound ", 404)
}

func (o *DeleteDockerNodecontainersNodecontainerNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
