// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewDeleteRolesNameUserEmailParams creates a new DeleteRolesNameUserEmailParams object
// with the default values initialized.
func NewDeleteRolesNameUserEmailParams() *DeleteRolesNameUserEmailParams {

	return &DeleteRolesNameUserEmailParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteRolesNameUserEmailParamsWithTimeout creates a new DeleteRolesNameUserEmailParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeleteRolesNameUserEmailParamsWithTimeout(timeout time.Duration) *DeleteRolesNameUserEmailParams {

	return &DeleteRolesNameUserEmailParams{

		timeout: timeout,
	}
}

// NewDeleteRolesNameUserEmailParamsWithContext creates a new DeleteRolesNameUserEmailParams object
// with the default values initialized, and the ability to set a context for a request
func NewDeleteRolesNameUserEmailParamsWithContext(ctx context.Context) *DeleteRolesNameUserEmailParams {

	return &DeleteRolesNameUserEmailParams{

		Context: ctx,
	}
}

// NewDeleteRolesNameUserEmailParamsWithHTTPClient creates a new DeleteRolesNameUserEmailParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDeleteRolesNameUserEmailParamsWithHTTPClient(client *http.Client) *DeleteRolesNameUserEmailParams {

	return &DeleteRolesNameUserEmailParams{
		HTTPClient: client,
	}
}

/*DeleteRolesNameUserEmailParams contains all the parameters to send to the API endpoint
for the delete roles name user email operation typically these are written to a http.Request
*/
type DeleteRolesNameUserEmailParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the delete roles name user email params
func (o *DeleteRolesNameUserEmailParams) WithTimeout(timeout time.Duration) *DeleteRolesNameUserEmailParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete roles name user email params
func (o *DeleteRolesNameUserEmailParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete roles name user email params
func (o *DeleteRolesNameUserEmailParams) WithContext(ctx context.Context) *DeleteRolesNameUserEmailParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete roles name user email params
func (o *DeleteRolesNameUserEmailParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete roles name user email params
func (o *DeleteRolesNameUserEmailParams) WithHTTPClient(client *http.Client) *DeleteRolesNameUserEmailParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete roles name user email params
func (o *DeleteRolesNameUserEmailParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteRolesNameUserEmailParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
