// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// DeleteServicesServiceTeamTeamReader is a Reader for the DeleteServicesServiceTeamTeam structure.
type DeleteServicesServiceTeamTeamReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteServicesServiceTeamTeamReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewDeleteServicesServiceTeamTeamOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewDeleteServicesServiceTeamTeamBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 401:
		result := NewDeleteServicesServiceTeamTeamUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 404:
		result := NewDeleteServicesServiceTeamTeamNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 409:
		result := NewDeleteServicesServiceTeamTeamConflict()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewDeleteServicesServiceTeamTeamOK creates a DeleteServicesServiceTeamTeamOK with default headers values
func NewDeleteServicesServiceTeamTeamOK() *DeleteServicesServiceTeamTeamOK {
	return &DeleteServicesServiceTeamTeamOK{}
}

/*DeleteServicesServiceTeamTeamOK handles this case with default header values.

Access revoked
*/
type DeleteServicesServiceTeamTeamOK struct {
}

func (o *DeleteServicesServiceTeamTeamOK) Error() string {
	return fmt.Sprintf("[DELETE /services/{service}/team/{team}][%d] deleteServicesServiceTeamTeamOK ", 200)
}

func (o *DeleteServicesServiceTeamTeamOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteServicesServiceTeamTeamBadRequest creates a DeleteServicesServiceTeamTeamBadRequest with default headers values
func NewDeleteServicesServiceTeamTeamBadRequest() *DeleteServicesServiceTeamTeamBadRequest {
	return &DeleteServicesServiceTeamTeamBadRequest{}
}

/*DeleteServicesServiceTeamTeamBadRequest handles this case with default header values.

Team not found
*/
type DeleteServicesServiceTeamTeamBadRequest struct {
}

func (o *DeleteServicesServiceTeamTeamBadRequest) Error() string {
	return fmt.Sprintf("[DELETE /services/{service}/team/{team}][%d] deleteServicesServiceTeamTeamBadRequest ", 400)
}

func (o *DeleteServicesServiceTeamTeamBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteServicesServiceTeamTeamUnauthorized creates a DeleteServicesServiceTeamTeamUnauthorized with default headers values
func NewDeleteServicesServiceTeamTeamUnauthorized() *DeleteServicesServiceTeamTeamUnauthorized {
	return &DeleteServicesServiceTeamTeamUnauthorized{}
}

/*DeleteServicesServiceTeamTeamUnauthorized handles this case with default header values.

Unauthorized
*/
type DeleteServicesServiceTeamTeamUnauthorized struct {
}

func (o *DeleteServicesServiceTeamTeamUnauthorized) Error() string {
	return fmt.Sprintf("[DELETE /services/{service}/team/{team}][%d] deleteServicesServiceTeamTeamUnauthorized ", 401)
}

func (o *DeleteServicesServiceTeamTeamUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteServicesServiceTeamTeamNotFound creates a DeleteServicesServiceTeamTeamNotFound with default headers values
func NewDeleteServicesServiceTeamTeamNotFound() *DeleteServicesServiceTeamTeamNotFound {
	return &DeleteServicesServiceTeamTeamNotFound{}
}

/*DeleteServicesServiceTeamTeamNotFound handles this case with default header values.

Service not found
*/
type DeleteServicesServiceTeamTeamNotFound struct {
}

func (o *DeleteServicesServiceTeamTeamNotFound) Error() string {
	return fmt.Sprintf("[DELETE /services/{service}/team/{team}][%d] deleteServicesServiceTeamTeamNotFound ", 404)
}

func (o *DeleteServicesServiceTeamTeamNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteServicesServiceTeamTeamConflict creates a DeleteServicesServiceTeamTeamConflict with default headers values
func NewDeleteServicesServiceTeamTeamConflict() *DeleteServicesServiceTeamTeamConflict {
	return &DeleteServicesServiceTeamTeamConflict{}
}

/*DeleteServicesServiceTeamTeamConflict handles this case with default header values.

Team does not has access to this service
*/
type DeleteServicesServiceTeamTeamConflict struct {
}

func (o *DeleteServicesServiceTeamTeamConflict) Error() string {
	return fmt.Sprintf("[DELETE /services/{service}/team/{team}][%d] deleteServicesServiceTeamTeamConflict ", 409)
}

func (o *DeleteServicesServiceTeamTeamConflict) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
