// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewDeletePlansNameParams creates a new DeletePlansNameParams object
// with the default values initialized.
func NewDeletePlansNameParams() *DeletePlansNameParams {

	return &DeletePlansNameParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeletePlansNameParamsWithTimeout creates a new DeletePlansNameParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeletePlansNameParamsWithTimeout(timeout time.Duration) *DeletePlansNameParams {

	return &DeletePlansNameParams{

		timeout: timeout,
	}
}

// NewDeletePlansNameParamsWithContext creates a new DeletePlansNameParams object
// with the default values initialized, and the ability to set a context for a request
func NewDeletePlansNameParamsWithContext(ctx context.Context) *DeletePlansNameParams {

	return &DeletePlansNameParams{

		Context: ctx,
	}
}

// NewDeletePlansNameParamsWithHTTPClient creates a new DeletePlansNameParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDeletePlansNameParamsWithHTTPClient(client *http.Client) *DeletePlansNameParams {

	return &DeletePlansNameParams{
		HTTPClient: client,
	}
}

/*DeletePlansNameParams contains all the parameters to send to the API endpoint
for the delete plans name operation typically these are written to a http.Request
*/
type DeletePlansNameParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the delete plans name params
func (o *DeletePlansNameParams) WithTimeout(timeout time.Duration) *DeletePlansNameParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete plans name params
func (o *DeletePlansNameParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete plans name params
func (o *DeletePlansNameParams) WithContext(ctx context.Context) *DeletePlansNameParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete plans name params
func (o *DeletePlansNameParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete plans name params
func (o *DeletePlansNameParams) WithHTTPClient(client *http.Client) *DeletePlansNameParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete plans name params
func (o *DeletePlansNameParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *DeletePlansNameParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
