// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewDeleteVolumesVolumeParams creates a new DeleteVolumesVolumeParams object
// with the default values initialized.
func NewDeleteVolumesVolumeParams() *DeleteVolumesVolumeParams {
	var ()
	return &DeleteVolumesVolumeParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteVolumesVolumeParamsWithTimeout creates a new DeleteVolumesVolumeParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeleteVolumesVolumeParamsWithTimeout(timeout time.Duration) *DeleteVolumesVolumeParams {
	var ()
	return &DeleteVolumesVolumeParams{

		timeout: timeout,
	}
}

// NewDeleteVolumesVolumeParamsWithContext creates a new DeleteVolumesVolumeParams object
// with the default values initialized, and the ability to set a context for a request
func NewDeleteVolumesVolumeParamsWithContext(ctx context.Context) *DeleteVolumesVolumeParams {
	var ()
	return &DeleteVolumesVolumeParams{

		Context: ctx,
	}
}

// NewDeleteVolumesVolumeParamsWithHTTPClient creates a new DeleteVolumesVolumeParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDeleteVolumesVolumeParamsWithHTTPClient(client *http.Client) *DeleteVolumesVolumeParams {
	var ()
	return &DeleteVolumesVolumeParams{
		HTTPClient: client,
	}
}

/*DeleteVolumesVolumeParams contains all the parameters to send to the API endpoint
for the delete volumes volume operation typically these are written to a http.Request
*/
type DeleteVolumesVolumeParams struct {

	/*Volume
	  Volume name.

	*/
	Volume string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the delete volumes volume params
func (o *DeleteVolumesVolumeParams) WithTimeout(timeout time.Duration) *DeleteVolumesVolumeParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete volumes volume params
func (o *DeleteVolumesVolumeParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete volumes volume params
func (o *DeleteVolumesVolumeParams) WithContext(ctx context.Context) *DeleteVolumesVolumeParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete volumes volume params
func (o *DeleteVolumesVolumeParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete volumes volume params
func (o *DeleteVolumesVolumeParams) WithHTTPClient(client *http.Client) *DeleteVolumesVolumeParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete volumes volume params
func (o *DeleteVolumesVolumeParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithVolume adds the volume to the delete volumes volume params
func (o *DeleteVolumesVolumeParams) WithVolume(volume string) *DeleteVolumesVolumeParams {
	o.SetVolume(volume)
	return o
}

// SetVolume adds the volume to the delete volumes volume params
func (o *DeleteVolumesVolumeParams) SetVolume(volume string) {
	o.Volume = volume
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteVolumesVolumeParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param volume
	if err := r.SetPathParam("volume", o.Volume); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
