// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// DeleteAutoscaleRulesIDReader is a Reader for the DeleteAutoscaleRulesID structure.
type DeleteAutoscaleRulesIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteAutoscaleRulesIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewDeleteAutoscaleRulesIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 401:
		result := NewDeleteAutoscaleRulesIDUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 404:
		result := NewDeleteAutoscaleRulesIDNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewDeleteAutoscaleRulesIDOK creates a DeleteAutoscaleRulesIDOK with default headers values
func NewDeleteAutoscaleRulesIDOK() *DeleteAutoscaleRulesIDOK {
	return &DeleteAutoscaleRulesIDOK{}
}

/*DeleteAutoscaleRulesIDOK handles this case with default header values.

Ok
*/
type DeleteAutoscaleRulesIDOK struct {
}

func (o *DeleteAutoscaleRulesIDOK) Error() string {
	return fmt.Sprintf("[DELETE /autoscale/rules/{id}][%d] deleteAutoscaleRulesIdOK ", 200)
}

func (o *DeleteAutoscaleRulesIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteAutoscaleRulesIDUnauthorized creates a DeleteAutoscaleRulesIDUnauthorized with default headers values
func NewDeleteAutoscaleRulesIDUnauthorized() *DeleteAutoscaleRulesIDUnauthorized {
	return &DeleteAutoscaleRulesIDUnauthorized{}
}

/*DeleteAutoscaleRulesIDUnauthorized handles this case with default header values.

Unauthorized
*/
type DeleteAutoscaleRulesIDUnauthorized struct {
}

func (o *DeleteAutoscaleRulesIDUnauthorized) Error() string {
	return fmt.Sprintf("[DELETE /autoscale/rules/{id}][%d] deleteAutoscaleRulesIdUnauthorized ", 401)
}

func (o *DeleteAutoscaleRulesIDUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteAutoscaleRulesIDNotFound creates a DeleteAutoscaleRulesIDNotFound with default headers values
func NewDeleteAutoscaleRulesIDNotFound() *DeleteAutoscaleRulesIDNotFound {
	return &DeleteAutoscaleRulesIDNotFound{}
}

/*DeleteAutoscaleRulesIDNotFound handles this case with default header values.

Not found
*/
type DeleteAutoscaleRulesIDNotFound struct {
}

func (o *DeleteAutoscaleRulesIDNotFound) Error() string {
	return fmt.Sprintf("[DELETE /autoscale/rules/{id}][%d] deleteAutoscaleRulesIdNotFound ", 404)
}

func (o *DeleteAutoscaleRulesIDNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
