// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// DeleteVolumesVolumeBindReader is a Reader for the DeleteVolumesVolumeBind structure.
type DeleteVolumesVolumeBindReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteVolumesVolumeBindReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewDeleteVolumesVolumeBindOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 401:
		result := NewDeleteVolumesVolumeBindUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 404:
		result := NewDeleteVolumesVolumeBindNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewDeleteVolumesVolumeBindOK creates a DeleteVolumesVolumeBindOK with default headers values
func NewDeleteVolumesVolumeBindOK() *DeleteVolumesVolumeBindOK {
	return &DeleteVolumesVolumeBindOK{}
}

/*DeleteVolumesVolumeBindOK handles this case with default header values.

Volume unbinded
*/
type DeleteVolumesVolumeBindOK struct {
}

func (o *DeleteVolumesVolumeBindOK) Error() string {
	return fmt.Sprintf("[DELETE /volumes/{volume}/bind][%d] deleteVolumesVolumeBindOK ", 200)
}

func (o *DeleteVolumesVolumeBindOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteVolumesVolumeBindUnauthorized creates a DeleteVolumesVolumeBindUnauthorized with default headers values
func NewDeleteVolumesVolumeBindUnauthorized() *DeleteVolumesVolumeBindUnauthorized {
	return &DeleteVolumesVolumeBindUnauthorized{}
}

/*DeleteVolumesVolumeBindUnauthorized handles this case with default header values.

Unauthorized
*/
type DeleteVolumesVolumeBindUnauthorized struct {
}

func (o *DeleteVolumesVolumeBindUnauthorized) Error() string {
	return fmt.Sprintf("[DELETE /volumes/{volume}/bind][%d] deleteVolumesVolumeBindUnauthorized ", 401)
}

func (o *DeleteVolumesVolumeBindUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteVolumesVolumeBindNotFound creates a DeleteVolumesVolumeBindNotFound with default headers values
func NewDeleteVolumesVolumeBindNotFound() *DeleteVolumesVolumeBindNotFound {
	return &DeleteVolumesVolumeBindNotFound{}
}

/*DeleteVolumesVolumeBindNotFound handles this case with default header values.

Volume not found
*/
type DeleteVolumesVolumeBindNotFound struct {
}

func (o *DeleteVolumesVolumeBindNotFound) Error() string {
	return fmt.Sprintf("[DELETE /volumes/{volume}/bind][%d] deleteVolumesVolumeBindNotFound ", 404)
}

func (o *DeleteVolumesVolumeBindNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
