// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewDeletePoolsNameParams creates a new DeletePoolsNameParams object
// with the default values initialized.
func NewDeletePoolsNameParams() *DeletePoolsNameParams {

	return &DeletePoolsNameParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeletePoolsNameParamsWithTimeout creates a new DeletePoolsNameParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeletePoolsNameParamsWithTimeout(timeout time.Duration) *DeletePoolsNameParams {

	return &DeletePoolsNameParams{

		timeout: timeout,
	}
}

// NewDeletePoolsNameParamsWithContext creates a new DeletePoolsNameParams object
// with the default values initialized, and the ability to set a context for a request
func NewDeletePoolsNameParamsWithContext(ctx context.Context) *DeletePoolsNameParams {

	return &DeletePoolsNameParams{

		Context: ctx,
	}
}

// NewDeletePoolsNameParamsWithHTTPClient creates a new DeletePoolsNameParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDeletePoolsNameParamsWithHTTPClient(client *http.Client) *DeletePoolsNameParams {

	return &DeletePoolsNameParams{
		HTTPClient: client,
	}
}

/*DeletePoolsNameParams contains all the parameters to send to the API endpoint
for the delete pools name operation typically these are written to a http.Request
*/
type DeletePoolsNameParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the delete pools name params
func (o *DeletePoolsNameParams) WithTimeout(timeout time.Duration) *DeletePoolsNameParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete pools name params
func (o *DeletePoolsNameParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete pools name params
func (o *DeletePoolsNameParams) WithContext(ctx context.Context) *DeletePoolsNameParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete pools name params
func (o *DeletePoolsNameParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete pools name params
func (o *DeletePoolsNameParams) WithHTTPClient(client *http.Client) *DeletePoolsNameParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete pools name params
func (o *DeletePoolsNameParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *DeletePoolsNameParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
