// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewDeleteEventsBlocksBlockParams creates a new DeleteEventsBlocksBlockParams object
// with the default values initialized.
func NewDeleteEventsBlocksBlockParams() *DeleteEventsBlocksBlockParams {
	var ()
	return &DeleteEventsBlocksBlockParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteEventsBlocksBlockParamsWithTimeout creates a new DeleteEventsBlocksBlockParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeleteEventsBlocksBlockParamsWithTimeout(timeout time.Duration) *DeleteEventsBlocksBlockParams {
	var ()
	return &DeleteEventsBlocksBlockParams{

		timeout: timeout,
	}
}

// NewDeleteEventsBlocksBlockParamsWithContext creates a new DeleteEventsBlocksBlockParams object
// with the default values initialized, and the ability to set a context for a request
func NewDeleteEventsBlocksBlockParamsWithContext(ctx context.Context) *DeleteEventsBlocksBlockParams {
	var ()
	return &DeleteEventsBlocksBlockParams{

		Context: ctx,
	}
}

// NewDeleteEventsBlocksBlockParamsWithHTTPClient creates a new DeleteEventsBlocksBlockParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDeleteEventsBlocksBlockParamsWithHTTPClient(client *http.Client) *DeleteEventsBlocksBlockParams {
	var ()
	return &DeleteEventsBlocksBlockParams{
		HTTPClient: client,
	}
}

/*DeleteEventsBlocksBlockParams contains all the parameters to send to the API endpoint
for the delete events blocks block operation typically these are written to a http.Request
*/
type DeleteEventsBlocksBlockParams struct {

	/*Block
	  Event block ID.

	*/
	Block string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the delete events blocks block params
func (o *DeleteEventsBlocksBlockParams) WithTimeout(timeout time.Duration) *DeleteEventsBlocksBlockParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete events blocks block params
func (o *DeleteEventsBlocksBlockParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete events blocks block params
func (o *DeleteEventsBlocksBlockParams) WithContext(ctx context.Context) *DeleteEventsBlocksBlockParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete events blocks block params
func (o *DeleteEventsBlocksBlockParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete events blocks block params
func (o *DeleteEventsBlocksBlockParams) WithHTTPClient(client *http.Client) *DeleteEventsBlocksBlockParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete events blocks block params
func (o *DeleteEventsBlocksBlockParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBlock adds the block to the delete events blocks block params
func (o *DeleteEventsBlocksBlockParams) WithBlock(block string) *DeleteEventsBlocksBlockParams {
	o.SetBlock(block)
	return o
}

// SetBlock adds the block to the delete events blocks block params
func (o *DeleteEventsBlocksBlockParams) SetBlock(block string) {
	o.Block = block
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteEventsBlocksBlockParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param block
	if err := r.SetPathParam("block", o.Block); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
