// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetRolesNameParams creates a new GetRolesNameParams object
// with the default values initialized.
func NewGetRolesNameParams() *GetRolesNameParams {

	return &GetRolesNameParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetRolesNameParamsWithTimeout creates a new GetRolesNameParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetRolesNameParamsWithTimeout(timeout time.Duration) *GetRolesNameParams {

	return &GetRolesNameParams{

		timeout: timeout,
	}
}

// NewGetRolesNameParamsWithContext creates a new GetRolesNameParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetRolesNameParamsWithContext(ctx context.Context) *GetRolesNameParams {

	return &GetRolesNameParams{

		Context: ctx,
	}
}

// NewGetRolesNameParamsWithHTTPClient creates a new GetRolesNameParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetRolesNameParamsWithHTTPClient(client *http.Client) *GetRolesNameParams {

	return &GetRolesNameParams{
		HTTPClient: client,
	}
}

/*GetRolesNameParams contains all the parameters to send to the API endpoint
for the get roles name operation typically these are written to a http.Request
*/
type GetRolesNameParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get roles name params
func (o *GetRolesNameParams) WithTimeout(timeout time.Duration) *GetRolesNameParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get roles name params
func (o *GetRolesNameParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get roles name params
func (o *GetRolesNameParams) WithContext(ctx context.Context) *GetRolesNameParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get roles name params
func (o *GetRolesNameParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get roles name params
func (o *GetRolesNameParams) WithHTTPClient(client *http.Client) *GetRolesNameParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get roles name params
func (o *GetRolesNameParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetRolesNameParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
