// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetAppsNameShellParams creates a new GetAppsNameShellParams object
// with the default values initialized.
func NewGetAppsNameShellParams() *GetAppsNameShellParams {

	return &GetAppsNameShellParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetAppsNameShellParamsWithTimeout creates a new GetAppsNameShellParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetAppsNameShellParamsWithTimeout(timeout time.Duration) *GetAppsNameShellParams {

	return &GetAppsNameShellParams{

		timeout: timeout,
	}
}

// NewGetAppsNameShellParamsWithContext creates a new GetAppsNameShellParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetAppsNameShellParamsWithContext(ctx context.Context) *GetAppsNameShellParams {

	return &GetAppsNameShellParams{

		Context: ctx,
	}
}

// NewGetAppsNameShellParamsWithHTTPClient creates a new GetAppsNameShellParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetAppsNameShellParamsWithHTTPClient(client *http.Client) *GetAppsNameShellParams {

	return &GetAppsNameShellParams{
		HTTPClient: client,
	}
}

/*GetAppsNameShellParams contains all the parameters to send to the API endpoint
for the get apps name shell operation typically these are written to a http.Request
*/
type GetAppsNameShellParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get apps name shell params
func (o *GetAppsNameShellParams) WithTimeout(timeout time.Duration) *GetAppsNameShellParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get apps name shell params
func (o *GetAppsNameShellParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get apps name shell params
func (o *GetAppsNameShellParams) WithContext(ctx context.Context) *GetAppsNameShellParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get apps name shell params
func (o *GetAppsNameShellParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get apps name shell params
func (o *GetAppsNameShellParams) WithHTTPClient(client *http.Client) *GetAppsNameShellParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get apps name shell params
func (o *GetAppsNameShellParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetAppsNameShellParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
