// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// GetIaasMachinesReader is a Reader for the GetIaasMachines structure.
type GetIaasMachinesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetIaasMachinesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetIaasMachinesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 401:
		result := NewGetIaasMachinesUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetIaasMachinesOK creates a GetIaasMachinesOK with default headers values
func NewGetIaasMachinesOK() *GetIaasMachinesOK {
	return &GetIaasMachinesOK{}
}

/*GetIaasMachinesOK handles this case with default header values.

OK
*/
type GetIaasMachinesOK struct {
}

func (o *GetIaasMachinesOK) Error() string {
	return fmt.Sprintf("[GET /iaas/machines][%d] getIaasMachinesOK ", 200)
}

func (o *GetIaasMachinesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetIaasMachinesUnauthorized creates a GetIaasMachinesUnauthorized with default headers values
func NewGetIaasMachinesUnauthorized() *GetIaasMachinesUnauthorized {
	return &GetIaasMachinesUnauthorized{}
}

/*GetIaasMachinesUnauthorized handles this case with default header values.

Unauthorized
*/
type GetIaasMachinesUnauthorized struct {
}

func (o *GetIaasMachinesUnauthorized) Error() string {
	return fmt.Sprintf("[GET /iaas/machines][%d] getIaasMachinesUnauthorized ", 401)
}

func (o *GetIaasMachinesUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
