// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetProvisionerClustersClusterParams creates a new GetProvisionerClustersClusterParams object
// with the default values initialized.
func NewGetProvisionerClustersClusterParams() *GetProvisionerClustersClusterParams {
	var ()
	return &GetProvisionerClustersClusterParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetProvisionerClustersClusterParamsWithTimeout creates a new GetProvisionerClustersClusterParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetProvisionerClustersClusterParamsWithTimeout(timeout time.Duration) *GetProvisionerClustersClusterParams {
	var ()
	return &GetProvisionerClustersClusterParams{

		timeout: timeout,
	}
}

// NewGetProvisionerClustersClusterParamsWithContext creates a new GetProvisionerClustersClusterParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetProvisionerClustersClusterParamsWithContext(ctx context.Context) *GetProvisionerClustersClusterParams {
	var ()
	return &GetProvisionerClustersClusterParams{

		Context: ctx,
	}
}

// NewGetProvisionerClustersClusterParamsWithHTTPClient creates a new GetProvisionerClustersClusterParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetProvisionerClustersClusterParamsWithHTTPClient(client *http.Client) *GetProvisionerClustersClusterParams {
	var ()
	return &GetProvisionerClustersClusterParams{
		HTTPClient: client,
	}
}

/*GetProvisionerClustersClusterParams contains all the parameters to send to the API endpoint
for the get provisioner clusters cluster operation typically these are written to a http.Request
*/
type GetProvisionerClustersClusterParams struct {

	/*Cluster
	  Cluster name.

	*/
	Cluster string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get provisioner clusters cluster params
func (o *GetProvisionerClustersClusterParams) WithTimeout(timeout time.Duration) *GetProvisionerClustersClusterParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get provisioner clusters cluster params
func (o *GetProvisionerClustersClusterParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get provisioner clusters cluster params
func (o *GetProvisionerClustersClusterParams) WithContext(ctx context.Context) *GetProvisionerClustersClusterParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get provisioner clusters cluster params
func (o *GetProvisionerClustersClusterParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get provisioner clusters cluster params
func (o *GetProvisionerClustersClusterParams) WithHTTPClient(client *http.Client) *GetProvisionerClustersClusterParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get provisioner clusters cluster params
func (o *GetProvisionerClustersClusterParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithCluster adds the cluster to the get provisioner clusters cluster params
func (o *GetProvisionerClustersClusterParams) WithCluster(cluster string) *GetProvisionerClustersClusterParams {
	o.SetCluster(cluster)
	return o
}

// SetCluster adds the cluster to the get provisioner clusters cluster params
func (o *GetProvisionerClustersClusterParams) SetCluster(cluster string) {
	o.Cluster = cluster
}

// WriteToRequest writes these params to a swagger request
func (o *GetProvisionerClustersClusterParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param cluster
	if err := r.SetPathParam("cluster", o.Cluster); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
