// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// GetServicesInstancesReader is a Reader for the GetServicesInstances structure.
type GetServicesInstancesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetServicesInstancesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetServicesInstancesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 204:
		result := NewGetServicesInstancesNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 401:
		result := NewGetServicesInstancesUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetServicesInstancesOK creates a GetServicesInstancesOK with default headers values
func NewGetServicesInstancesOK() *GetServicesInstancesOK {
	return &GetServicesInstancesOK{}
}

/*GetServicesInstancesOK handles this case with default header values.

List services instances
*/
type GetServicesInstancesOK struct {
}

func (o *GetServicesInstancesOK) Error() string {
	return fmt.Sprintf("[GET /services/instances][%d] getServicesInstancesOK ", 200)
}

func (o *GetServicesInstancesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetServicesInstancesNoContent creates a GetServicesInstancesNoContent with default headers values
func NewGetServicesInstancesNoContent() *GetServicesInstancesNoContent {
	return &GetServicesInstancesNoContent{}
}

/*GetServicesInstancesNoContent handles this case with default header values.

No content
*/
type GetServicesInstancesNoContent struct {
}

func (o *GetServicesInstancesNoContent) Error() string {
	return fmt.Sprintf("[GET /services/instances][%d] getServicesInstancesNoContent ", 204)
}

func (o *GetServicesInstancesNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetServicesInstancesUnauthorized creates a GetServicesInstancesUnauthorized with default headers values
func NewGetServicesInstancesUnauthorized() *GetServicesInstancesUnauthorized {
	return &GetServicesInstancesUnauthorized{}
}

/*GetServicesInstancesUnauthorized handles this case with default header values.

Unauthorized
*/
type GetServicesInstancesUnauthorized struct {
}

func (o *GetServicesInstancesUnauthorized) Error() string {
	return fmt.Sprintf("[GET /services/instances][%d] getServicesInstancesUnauthorized ", 401)
}

func (o *GetServicesInstancesUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
