// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetInstallHostsHostParams creates a new GetInstallHostsHostParams object
// with the default values initialized.
func NewGetInstallHostsHostParams() *GetInstallHostsHostParams {
	var ()
	return &GetInstallHostsHostParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetInstallHostsHostParamsWithTimeout creates a new GetInstallHostsHostParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetInstallHostsHostParamsWithTimeout(timeout time.Duration) *GetInstallHostsHostParams {
	var ()
	return &GetInstallHostsHostParams{

		timeout: timeout,
	}
}

// NewGetInstallHostsHostParamsWithContext creates a new GetInstallHostsHostParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetInstallHostsHostParamsWithContext(ctx context.Context) *GetInstallHostsHostParams {
	var ()
	return &GetInstallHostsHostParams{

		Context: ctx,
	}
}

// NewGetInstallHostsHostParamsWithHTTPClient creates a new GetInstallHostsHostParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetInstallHostsHostParamsWithHTTPClient(client *http.Client) *GetInstallHostsHostParams {
	var ()
	return &GetInstallHostsHostParams{
		HTTPClient: client,
	}
}

/*GetInstallHostsHostParams contains all the parameters to send to the API endpoint
for the get install hosts host operation typically these are written to a http.Request
*/
type GetInstallHostsHostParams struct {

	/*Host
	  Host name.

	*/
	Host string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get install hosts host params
func (o *GetInstallHostsHostParams) WithTimeout(timeout time.Duration) *GetInstallHostsHostParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get install hosts host params
func (o *GetInstallHostsHostParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get install hosts host params
func (o *GetInstallHostsHostParams) WithContext(ctx context.Context) *GetInstallHostsHostParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get install hosts host params
func (o *GetInstallHostsHostParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get install hosts host params
func (o *GetInstallHostsHostParams) WithHTTPClient(client *http.Client) *GetInstallHostsHostParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get install hosts host params
func (o *GetInstallHostsHostParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithHost adds the host to the get install hosts host params
func (o *GetInstallHostsHostParams) WithHost(host string) *GetInstallHostsHostParams {
	o.SetHost(host)
	return o
}

// SetHost adds the host to the get install hosts host params
func (o *GetInstallHostsHostParams) SetHost(host string) {
	o.Host = host
}

// WriteToRequest writes these params to a swagger request
func (o *GetInstallHostsHostParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param host
	if err := r.SetPathParam("host", o.Host); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
