// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// GetAppAppRoutersReader is a Reader for the GetAppAppRouters structure.
type GetAppAppRoutersReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAppAppRoutersReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetAppAppRoutersOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 204:
		result := NewGetAppAppRoutersNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 404:
		result := NewGetAppAppRoutersNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetAppAppRoutersOK creates a GetAppAppRoutersOK with default headers values
func NewGetAppAppRoutersOK() *GetAppAppRoutersOK {
	return &GetAppAppRoutersOK{}
}

/*GetAppAppRoutersOK handles this case with default header values.

OK
*/
type GetAppAppRoutersOK struct {
}

func (o *GetAppAppRoutersOK) Error() string {
	return fmt.Sprintf("[GET /app/{app}/routers][%d] getAppAppRoutersOK ", 200)
}

func (o *GetAppAppRoutersOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetAppAppRoutersNoContent creates a GetAppAppRoutersNoContent with default headers values
func NewGetAppAppRoutersNoContent() *GetAppAppRoutersNoContent {
	return &GetAppAppRoutersNoContent{}
}

/*GetAppAppRoutersNoContent handles this case with default header values.

No content
*/
type GetAppAppRoutersNoContent struct {
}

func (o *GetAppAppRoutersNoContent) Error() string {
	return fmt.Sprintf("[GET /app/{app}/routers][%d] getAppAppRoutersNoContent ", 204)
}

func (o *GetAppAppRoutersNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetAppAppRoutersNotFound creates a GetAppAppRoutersNotFound with default headers values
func NewGetAppAppRoutersNotFound() *GetAppAppRoutersNotFound {
	return &GetAppAppRoutersNotFound{}
}

/*GetAppAppRoutersNotFound handles this case with default header values.

App not found
*/
type GetAppAppRoutersNotFound struct {
}

func (o *GetAppAppRoutersNotFound) Error() string {
	return fmt.Sprintf("[GET /app/{app}/routers][%d] getAppAppRoutersNotFound ", 404)
}

func (o *GetAppAppRoutersNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
