// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetDebugPprofParams creates a new GetDebugPprofParams object
// with the default values initialized.
func NewGetDebugPprofParams() *GetDebugPprofParams {

	return &GetDebugPprofParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetDebugPprofParamsWithTimeout creates a new GetDebugPprofParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetDebugPprofParamsWithTimeout(timeout time.Duration) *GetDebugPprofParams {

	return &GetDebugPprofParams{

		timeout: timeout,
	}
}

// NewGetDebugPprofParamsWithContext creates a new GetDebugPprofParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetDebugPprofParamsWithContext(ctx context.Context) *GetDebugPprofParams {

	return &GetDebugPprofParams{

		Context: ctx,
	}
}

// NewGetDebugPprofParamsWithHTTPClient creates a new GetDebugPprofParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetDebugPprofParamsWithHTTPClient(client *http.Client) *GetDebugPprofParams {

	return &GetDebugPprofParams{
		HTTPClient: client,
	}
}

/*GetDebugPprofParams contains all the parameters to send to the API endpoint
for the get debug pprof operation typically these are written to a http.Request
*/
type GetDebugPprofParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get debug pprof params
func (o *GetDebugPprofParams) WithTimeout(timeout time.Duration) *GetDebugPprofParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get debug pprof params
func (o *GetDebugPprofParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get debug pprof params
func (o *GetDebugPprofParams) WithContext(ctx context.Context) *GetDebugPprofParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get debug pprof params
func (o *GetDebugPprofParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get debug pprof params
func (o *GetDebugPprofParams) WithHTTPClient(client *http.Client) *GetDebugPprofParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get debug pprof params
func (o *GetDebugPprofParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetDebugPprofParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
