// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// GetAppsAppMetricEnvsReader is a Reader for the GetAppsAppMetricEnvs structure.
type GetAppsAppMetricEnvsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAppsAppMetricEnvsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetAppsAppMetricEnvsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 401:
		result := NewGetAppsAppMetricEnvsUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 404:
		result := NewGetAppsAppMetricEnvsNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetAppsAppMetricEnvsOK creates a GetAppsAppMetricEnvsOK with default headers values
func NewGetAppsAppMetricEnvsOK() *GetAppsAppMetricEnvsOK {
	return &GetAppsAppMetricEnvsOK{}
}

/*GetAppsAppMetricEnvsOK handles this case with default header values.

Ok
*/
type GetAppsAppMetricEnvsOK struct {
}

func (o *GetAppsAppMetricEnvsOK) Error() string {
	return fmt.Sprintf("[GET /apps/{app}/metric/envs][%d] getAppsAppMetricEnvsOK ", 200)
}

func (o *GetAppsAppMetricEnvsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetAppsAppMetricEnvsUnauthorized creates a GetAppsAppMetricEnvsUnauthorized with default headers values
func NewGetAppsAppMetricEnvsUnauthorized() *GetAppsAppMetricEnvsUnauthorized {
	return &GetAppsAppMetricEnvsUnauthorized{}
}

/*GetAppsAppMetricEnvsUnauthorized handles this case with default header values.

Unauthorized
*/
type GetAppsAppMetricEnvsUnauthorized struct {
}

func (o *GetAppsAppMetricEnvsUnauthorized) Error() string {
	return fmt.Sprintf("[GET /apps/{app}/metric/envs][%d] getAppsAppMetricEnvsUnauthorized ", 401)
}

func (o *GetAppsAppMetricEnvsUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetAppsAppMetricEnvsNotFound creates a GetAppsAppMetricEnvsNotFound with default headers values
func NewGetAppsAppMetricEnvsNotFound() *GetAppsAppMetricEnvsNotFound {
	return &GetAppsAppMetricEnvsNotFound{}
}

/*GetAppsAppMetricEnvsNotFound handles this case with default header values.

App not found
*/
type GetAppsAppMetricEnvsNotFound struct {
}

func (o *GetAppsAppMetricEnvsNotFound) Error() string {
	return fmt.Sprintf("[GET /apps/{app}/metric/envs][%d] getAppsAppMetricEnvsNotFound ", 404)
}

func (o *GetAppsAppMetricEnvsNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
