// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetDebugGoroutinesParams creates a new GetDebugGoroutinesParams object
// with the default values initialized.
func NewGetDebugGoroutinesParams() *GetDebugGoroutinesParams {

	return &GetDebugGoroutinesParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetDebugGoroutinesParamsWithTimeout creates a new GetDebugGoroutinesParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetDebugGoroutinesParamsWithTimeout(timeout time.Duration) *GetDebugGoroutinesParams {

	return &GetDebugGoroutinesParams{

		timeout: timeout,
	}
}

// NewGetDebugGoroutinesParamsWithContext creates a new GetDebugGoroutinesParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetDebugGoroutinesParamsWithContext(ctx context.Context) *GetDebugGoroutinesParams {

	return &GetDebugGoroutinesParams{

		Context: ctx,
	}
}

// NewGetDebugGoroutinesParamsWithHTTPClient creates a new GetDebugGoroutinesParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetDebugGoroutinesParamsWithHTTPClient(client *http.Client) *GetDebugGoroutinesParams {

	return &GetDebugGoroutinesParams{
		HTTPClient: client,
	}
}

/*GetDebugGoroutinesParams contains all the parameters to send to the API endpoint
for the get debug goroutines operation typically these are written to a http.Request
*/
type GetDebugGoroutinesParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get debug goroutines params
func (o *GetDebugGoroutinesParams) WithTimeout(timeout time.Duration) *GetDebugGoroutinesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get debug goroutines params
func (o *GetDebugGoroutinesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get debug goroutines params
func (o *GetDebugGoroutinesParams) WithContext(ctx context.Context) *GetDebugGoroutinesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get debug goroutines params
func (o *GetDebugGoroutinesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get debug goroutines params
func (o *GetDebugGoroutinesParams) WithHTTPClient(client *http.Client) *GetDebugGoroutinesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get debug goroutines params
func (o *GetDebugGoroutinesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetDebugGoroutinesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
