// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetServicesNameParams creates a new GetServicesNameParams object
// with the default values initialized.
func NewGetServicesNameParams() *GetServicesNameParams {

	return &GetServicesNameParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetServicesNameParamsWithTimeout creates a new GetServicesNameParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetServicesNameParamsWithTimeout(timeout time.Duration) *GetServicesNameParams {

	return &GetServicesNameParams{

		timeout: timeout,
	}
}

// NewGetServicesNameParamsWithContext creates a new GetServicesNameParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetServicesNameParamsWithContext(ctx context.Context) *GetServicesNameParams {

	return &GetServicesNameParams{

		Context: ctx,
	}
}

// NewGetServicesNameParamsWithHTTPClient creates a new GetServicesNameParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetServicesNameParamsWithHTTPClient(client *http.Client) *GetServicesNameParams {

	return &GetServicesNameParams{
		HTTPClient: client,
	}
}

/*GetServicesNameParams contains all the parameters to send to the API endpoint
for the get services name operation typically these are written to a http.Request
*/
type GetServicesNameParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get services name params
func (o *GetServicesNameParams) WithTimeout(timeout time.Duration) *GetServicesNameParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get services name params
func (o *GetServicesNameParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get services name params
func (o *GetServicesNameParams) WithContext(ctx context.Context) *GetServicesNameParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get services name params
func (o *GetServicesNameParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get services name params
func (o *GetServicesNameParams) WithHTTPClient(client *http.Client) *GetServicesNameParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get services name params
func (o *GetServicesNameParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetServicesNameParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
