// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// GetVolumeplansReader is a Reader for the GetVolumeplans structure.
type GetVolumeplansReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetVolumeplansReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetVolumeplansOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 401:
		result := NewGetVolumeplansUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetVolumeplansOK creates a GetVolumeplansOK with default headers values
func NewGetVolumeplansOK() *GetVolumeplansOK {
	return &GetVolumeplansOK{}
}

/*GetVolumeplansOK handles this case with default header values.

List volume plans
*/
type GetVolumeplansOK struct {
}

func (o *GetVolumeplansOK) Error() string {
	return fmt.Sprintf("[GET /volumeplans][%d] getVolumeplansOK ", 200)
}

func (o *GetVolumeplansOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetVolumeplansUnauthorized creates a GetVolumeplansUnauthorized with default headers values
func NewGetVolumeplansUnauthorized() *GetVolumeplansUnauthorized {
	return &GetVolumeplansUnauthorized{}
}

/*GetVolumeplansUnauthorized handles this case with default header values.

Unauthorized
*/
type GetVolumeplansUnauthorized struct {
}

func (o *GetVolumeplansUnauthorized) Error() string {
	return fmt.Sprintf("[GET /volumeplans][%d] getVolumeplansUnauthorized ", 401)
}

func (o *GetVolumeplansUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
