// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetServicesServiceProxyInstanceParams creates a new GetServicesServiceProxyInstanceParams object
// with the default values initialized.
func NewGetServicesServiceProxyInstanceParams() *GetServicesServiceProxyInstanceParams {
	var ()
	return &GetServicesServiceProxyInstanceParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetServicesServiceProxyInstanceParamsWithTimeout creates a new GetServicesServiceProxyInstanceParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetServicesServiceProxyInstanceParamsWithTimeout(timeout time.Duration) *GetServicesServiceProxyInstanceParams {
	var ()
	return &GetServicesServiceProxyInstanceParams{

		timeout: timeout,
	}
}

// NewGetServicesServiceProxyInstanceParamsWithContext creates a new GetServicesServiceProxyInstanceParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetServicesServiceProxyInstanceParamsWithContext(ctx context.Context) *GetServicesServiceProxyInstanceParams {
	var ()
	return &GetServicesServiceProxyInstanceParams{

		Context: ctx,
	}
}

// NewGetServicesServiceProxyInstanceParamsWithHTTPClient creates a new GetServicesServiceProxyInstanceParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetServicesServiceProxyInstanceParamsWithHTTPClient(client *http.Client) *GetServicesServiceProxyInstanceParams {
	var ()
	return &GetServicesServiceProxyInstanceParams{
		HTTPClient: client,
	}
}

/*GetServicesServiceProxyInstanceParams contains all the parameters to send to the API endpoint
for the get services service proxy instance operation typically these are written to a http.Request
*/
type GetServicesServiceProxyInstanceParams struct {

	/*Instance
	  Instance name.

	*/
	Instance string
	/*Service
	  Service name.

	*/
	Service string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get services service proxy instance params
func (o *GetServicesServiceProxyInstanceParams) WithTimeout(timeout time.Duration) *GetServicesServiceProxyInstanceParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get services service proxy instance params
func (o *GetServicesServiceProxyInstanceParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get services service proxy instance params
func (o *GetServicesServiceProxyInstanceParams) WithContext(ctx context.Context) *GetServicesServiceProxyInstanceParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get services service proxy instance params
func (o *GetServicesServiceProxyInstanceParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get services service proxy instance params
func (o *GetServicesServiceProxyInstanceParams) WithHTTPClient(client *http.Client) *GetServicesServiceProxyInstanceParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get services service proxy instance params
func (o *GetServicesServiceProxyInstanceParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithInstance adds the instance to the get services service proxy instance params
func (o *GetServicesServiceProxyInstanceParams) WithInstance(instance string) *GetServicesServiceProxyInstanceParams {
	o.SetInstance(instance)
	return o
}

// SetInstance adds the instance to the get services service proxy instance params
func (o *GetServicesServiceProxyInstanceParams) SetInstance(instance string) {
	o.Instance = instance
}

// WithService adds the service to the get services service proxy instance params
func (o *GetServicesServiceProxyInstanceParams) WithService(service string) *GetServicesServiceProxyInstanceParams {
	o.SetService(service)
	return o
}

// SetService adds the service to the get services service proxy instance params
func (o *GetServicesServiceProxyInstanceParams) SetService(service string) {
	o.Service = service
}

// WriteToRequest writes these params to a swagger request
func (o *GetServicesServiceProxyInstanceParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param instance
	if err := r.SetPathParam("instance", o.Instance); err != nil {
		return err
	}

	// path param service
	if err := r.SetPathParam("service", o.Service); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
