// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetServicesServiceDocParams creates a new GetServicesServiceDocParams object
// with the default values initialized.
func NewGetServicesServiceDocParams() *GetServicesServiceDocParams {
	var ()
	return &GetServicesServiceDocParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetServicesServiceDocParamsWithTimeout creates a new GetServicesServiceDocParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetServicesServiceDocParamsWithTimeout(timeout time.Duration) *GetServicesServiceDocParams {
	var ()
	return &GetServicesServiceDocParams{

		timeout: timeout,
	}
}

// NewGetServicesServiceDocParamsWithContext creates a new GetServicesServiceDocParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetServicesServiceDocParamsWithContext(ctx context.Context) *GetServicesServiceDocParams {
	var ()
	return &GetServicesServiceDocParams{

		Context: ctx,
	}
}

// NewGetServicesServiceDocParamsWithHTTPClient creates a new GetServicesServiceDocParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetServicesServiceDocParamsWithHTTPClient(client *http.Client) *GetServicesServiceDocParams {
	var ()
	return &GetServicesServiceDocParams{
		HTTPClient: client,
	}
}

/*GetServicesServiceDocParams contains all the parameters to send to the API endpoint
for the get services service doc operation typically these are written to a http.Request
*/
type GetServicesServiceDocParams struct {

	/*Service
	  Service name.

	*/
	Service string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get services service doc params
func (o *GetServicesServiceDocParams) WithTimeout(timeout time.Duration) *GetServicesServiceDocParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get services service doc params
func (o *GetServicesServiceDocParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get services service doc params
func (o *GetServicesServiceDocParams) WithContext(ctx context.Context) *GetServicesServiceDocParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get services service doc params
func (o *GetServicesServiceDocParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get services service doc params
func (o *GetServicesServiceDocParams) WithHTTPClient(client *http.Client) *GetServicesServiceDocParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get services service doc params
func (o *GetServicesServiceDocParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithService adds the service to the get services service doc params
func (o *GetServicesServiceDocParams) WithService(service string) *GetServicesServiceDocParams {
	o.SetService(service)
	return o
}

// SetService adds the service to the get services service doc params
func (o *GetServicesServiceDocParams) SetService(service string) {
	o.Service = service
}

// WriteToRequest writes these params to a swagger request
func (o *GetServicesServiceDocParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param service
	if err := r.SetPathParam("service", o.Service); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
