// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetVolumeplansParams creates a new GetVolumeplansParams object
// with the default values initialized.
func NewGetVolumeplansParams() *GetVolumeplansParams {

	return &GetVolumeplansParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetVolumeplansParamsWithTimeout creates a new GetVolumeplansParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetVolumeplansParamsWithTimeout(timeout time.Duration) *GetVolumeplansParams {

	return &GetVolumeplansParams{

		timeout: timeout,
	}
}

// NewGetVolumeplansParamsWithContext creates a new GetVolumeplansParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetVolumeplansParamsWithContext(ctx context.Context) *GetVolumeplansParams {

	return &GetVolumeplansParams{

		Context: ctx,
	}
}

// NewGetVolumeplansParamsWithHTTPClient creates a new GetVolumeplansParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetVolumeplansParamsWithHTTPClient(client *http.Client) *GetVolumeplansParams {

	return &GetVolumeplansParams{
		HTTPClient: client,
	}
}

/*GetVolumeplansParams contains all the parameters to send to the API endpoint
for the get volumeplans operation typically these are written to a http.Request
*/
type GetVolumeplansParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get volumeplans params
func (o *GetVolumeplansParams) WithTimeout(timeout time.Duration) *GetVolumeplansParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get volumeplans params
func (o *GetVolumeplansParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get volumeplans params
func (o *GetVolumeplansParams) WithContext(ctx context.Context) *GetVolumeplansParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get volumeplans params
func (o *GetVolumeplansParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get volumeplans params
func (o *GetVolumeplansParams) WithHTTPClient(client *http.Client) *GetVolumeplansParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get volumeplans params
func (o *GetVolumeplansParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetVolumeplansParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
