// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetEventsEventParams creates a new GetEventsEventParams object
// with the default values initialized.
func NewGetEventsEventParams() *GetEventsEventParams {
	var ()
	return &GetEventsEventParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetEventsEventParamsWithTimeout creates a new GetEventsEventParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetEventsEventParamsWithTimeout(timeout time.Duration) *GetEventsEventParams {
	var ()
	return &GetEventsEventParams{

		timeout: timeout,
	}
}

// NewGetEventsEventParamsWithContext creates a new GetEventsEventParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetEventsEventParamsWithContext(ctx context.Context) *GetEventsEventParams {
	var ()
	return &GetEventsEventParams{

		Context: ctx,
	}
}

// NewGetEventsEventParamsWithHTTPClient creates a new GetEventsEventParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetEventsEventParamsWithHTTPClient(client *http.Client) *GetEventsEventParams {
	var ()
	return &GetEventsEventParams{
		HTTPClient: client,
	}
}

/*GetEventsEventParams contains all the parameters to send to the API endpoint
for the get events event operation typically these are written to a http.Request
*/
type GetEventsEventParams struct {

	/*Event
	  Event ID.

	*/
	Event string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get events event params
func (o *GetEventsEventParams) WithTimeout(timeout time.Duration) *GetEventsEventParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get events event params
func (o *GetEventsEventParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get events event params
func (o *GetEventsEventParams) WithContext(ctx context.Context) *GetEventsEventParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get events event params
func (o *GetEventsEventParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get events event params
func (o *GetEventsEventParams) WithHTTPClient(client *http.Client) *GetEventsEventParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get events event params
func (o *GetEventsEventParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithEvent adds the event to the get events event params
func (o *GetEventsEventParams) WithEvent(event string) *GetEventsEventParams {
	o.SetEvent(event)
	return o
}

// SetEvent adds the event to the get events event params
func (o *GetEventsEventParams) SetEvent(event string) {
	o.Event = event
}

// WriteToRequest writes these params to a swagger request
func (o *GetEventsEventParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param event
	if err := r.SetPathParam("event", o.Event); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
