// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// GetAuthSchemeReader is a Reader for the GetAuthScheme structure.
type GetAuthSchemeReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAuthSchemeReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetAuthSchemeOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetAuthSchemeOK creates a GetAuthSchemeOK with default headers values
func NewGetAuthSchemeOK() *GetAuthSchemeOK {
	return &GetAuthSchemeOK{}
}

/*GetAuthSchemeOK handles this case with default header values.

OK
*/
type GetAuthSchemeOK struct {
}

func (o *GetAuthSchemeOK) Error() string {
	return fmt.Sprintf("[GET /auth/scheme][%d] getAuthSchemeOK ", 200)
}

func (o *GetAuthSchemeOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
