// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// GetServicesServiceInstancesInstanceStatusReader is a Reader for the GetServicesServiceInstancesInstanceStatus structure.
type GetServicesServiceInstancesInstanceStatusReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetServicesServiceInstancesInstanceStatusReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetServicesServiceInstancesInstanceStatusOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 401:
		result := NewGetServicesServiceInstancesInstanceStatusUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 404:
		result := NewGetServicesServiceInstancesInstanceStatusNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetServicesServiceInstancesInstanceStatusOK creates a GetServicesServiceInstancesInstanceStatusOK with default headers values
func NewGetServicesServiceInstancesInstanceStatusOK() *GetServicesServiceInstancesInstanceStatusOK {
	return &GetServicesServiceInstancesInstanceStatusOK{}
}

/*GetServicesServiceInstancesInstanceStatusOK handles this case with default header values.

List services instances
*/
type GetServicesServiceInstancesInstanceStatusOK struct {
}

func (o *GetServicesServiceInstancesInstanceStatusOK) Error() string {
	return fmt.Sprintf("[GET /services/{service}/instances/{instance}/status][%d] getServicesServiceInstancesInstanceStatusOK ", 200)
}

func (o *GetServicesServiceInstancesInstanceStatusOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetServicesServiceInstancesInstanceStatusUnauthorized creates a GetServicesServiceInstancesInstanceStatusUnauthorized with default headers values
func NewGetServicesServiceInstancesInstanceStatusUnauthorized() *GetServicesServiceInstancesInstanceStatusUnauthorized {
	return &GetServicesServiceInstancesInstanceStatusUnauthorized{}
}

/*GetServicesServiceInstancesInstanceStatusUnauthorized handles this case with default header values.

Unauthorized
*/
type GetServicesServiceInstancesInstanceStatusUnauthorized struct {
}

func (o *GetServicesServiceInstancesInstanceStatusUnauthorized) Error() string {
	return fmt.Sprintf("[GET /services/{service}/instances/{instance}/status][%d] getServicesServiceInstancesInstanceStatusUnauthorized ", 401)
}

func (o *GetServicesServiceInstancesInstanceStatusUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetServicesServiceInstancesInstanceStatusNotFound creates a GetServicesServiceInstancesInstanceStatusNotFound with default headers values
func NewGetServicesServiceInstancesInstanceStatusNotFound() *GetServicesServiceInstancesInstanceStatusNotFound {
	return &GetServicesServiceInstancesInstanceStatusNotFound{}
}

/*GetServicesServiceInstancesInstanceStatusNotFound handles this case with default header values.

Service instance not found
*/
type GetServicesServiceInstancesInstanceStatusNotFound struct {
}

func (o *GetServicesServiceInstancesInstanceStatusNotFound) Error() string {
	return fmt.Sprintf("[GET /services/{service}/instances/{instance}/status][%d] getServicesServiceInstancesInstanceStatusNotFound ", 404)
}

func (o *GetServicesServiceInstancesInstanceStatusNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
