// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// GetDockerNodeAppsAppnameContainersReader is a Reader for the GetDockerNodeAppsAppnameContainers structure.
type GetDockerNodeAppsAppnameContainersReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetDockerNodeAppsAppnameContainersReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetDockerNodeAppsAppnameContainersOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 204:
		result := NewGetDockerNodeAppsAppnameContainersNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 401:
		result := NewGetDockerNodeAppsAppnameContainersUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 404:
		result := NewGetDockerNodeAppsAppnameContainersNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetDockerNodeAppsAppnameContainersOK creates a GetDockerNodeAppsAppnameContainersOK with default headers values
func NewGetDockerNodeAppsAppnameContainersOK() *GetDockerNodeAppsAppnameContainersOK {
	return &GetDockerNodeAppsAppnameContainersOK{}
}

/*GetDockerNodeAppsAppnameContainersOK handles this case with default header values.

Ok
*/
type GetDockerNodeAppsAppnameContainersOK struct {
}

func (o *GetDockerNodeAppsAppnameContainersOK) Error() string {
	return fmt.Sprintf("[GET /docker/node/apps/{appname}/containers][%d] getDockerNodeAppsAppnameContainersOK ", 200)
}

func (o *GetDockerNodeAppsAppnameContainersOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetDockerNodeAppsAppnameContainersNoContent creates a GetDockerNodeAppsAppnameContainersNoContent with default headers values
func NewGetDockerNodeAppsAppnameContainersNoContent() *GetDockerNodeAppsAppnameContainersNoContent {
	return &GetDockerNodeAppsAppnameContainersNoContent{}
}

/*GetDockerNodeAppsAppnameContainersNoContent handles this case with default header values.

No content
*/
type GetDockerNodeAppsAppnameContainersNoContent struct {
}

func (o *GetDockerNodeAppsAppnameContainersNoContent) Error() string {
	return fmt.Sprintf("[GET /docker/node/apps/{appname}/containers][%d] getDockerNodeAppsAppnameContainersNoContent ", 204)
}

func (o *GetDockerNodeAppsAppnameContainersNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetDockerNodeAppsAppnameContainersUnauthorized creates a GetDockerNodeAppsAppnameContainersUnauthorized with default headers values
func NewGetDockerNodeAppsAppnameContainersUnauthorized() *GetDockerNodeAppsAppnameContainersUnauthorized {
	return &GetDockerNodeAppsAppnameContainersUnauthorized{}
}

/*GetDockerNodeAppsAppnameContainersUnauthorized handles this case with default header values.

Unauthorized
*/
type GetDockerNodeAppsAppnameContainersUnauthorized struct {
}

func (o *GetDockerNodeAppsAppnameContainersUnauthorized) Error() string {
	return fmt.Sprintf("[GET /docker/node/apps/{appname}/containers][%d] getDockerNodeAppsAppnameContainersUnauthorized ", 401)
}

func (o *GetDockerNodeAppsAppnameContainersUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetDockerNodeAppsAppnameContainersNotFound creates a GetDockerNodeAppsAppnameContainersNotFound with default headers values
func NewGetDockerNodeAppsAppnameContainersNotFound() *GetDockerNodeAppsAppnameContainersNotFound {
	return &GetDockerNodeAppsAppnameContainersNotFound{}
}

/*GetDockerNodeAppsAppnameContainersNotFound handles this case with default header values.

Not found
*/
type GetDockerNodeAppsAppnameContainersNotFound struct {
}

func (o *GetDockerNodeAppsAppnameContainersNotFound) Error() string {
	return fmt.Sprintf("[GET /docker/node/apps/{appname}/containers][%d] getDockerNodeAppsAppnameContainersNotFound ", 404)
}

func (o *GetDockerNodeAppsAppnameContainersNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
