// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// GetProvisionerNodeAddressContainersReader is a Reader for the GetProvisionerNodeAddressContainers structure.
type GetProvisionerNodeAddressContainersReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetProvisionerNodeAddressContainersReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetProvisionerNodeAddressContainersOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 204:
		result := NewGetProvisionerNodeAddressContainersNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 401:
		result := NewGetProvisionerNodeAddressContainersUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 404:
		result := NewGetProvisionerNodeAddressContainersNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetProvisionerNodeAddressContainersOK creates a GetProvisionerNodeAddressContainersOK with default headers values
func NewGetProvisionerNodeAddressContainersOK() *GetProvisionerNodeAddressContainersOK {
	return &GetProvisionerNodeAddressContainersOK{}
}

/*GetProvisionerNodeAddressContainersOK handles this case with default header values.

Ok
*/
type GetProvisionerNodeAddressContainersOK struct {
}

func (o *GetProvisionerNodeAddressContainersOK) Error() string {
	return fmt.Sprintf("[GET /{provisioner}/node/{address}/containers][%d] getProvisionerNodeAddressContainersOK ", 200)
}

func (o *GetProvisionerNodeAddressContainersOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetProvisionerNodeAddressContainersNoContent creates a GetProvisionerNodeAddressContainersNoContent with default headers values
func NewGetProvisionerNodeAddressContainersNoContent() *GetProvisionerNodeAddressContainersNoContent {
	return &GetProvisionerNodeAddressContainersNoContent{}
}

/*GetProvisionerNodeAddressContainersNoContent handles this case with default header values.

No content
*/
type GetProvisionerNodeAddressContainersNoContent struct {
}

func (o *GetProvisionerNodeAddressContainersNoContent) Error() string {
	return fmt.Sprintf("[GET /{provisioner}/node/{address}/containers][%d] getProvisionerNodeAddressContainersNoContent ", 204)
}

func (o *GetProvisionerNodeAddressContainersNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetProvisionerNodeAddressContainersUnauthorized creates a GetProvisionerNodeAddressContainersUnauthorized with default headers values
func NewGetProvisionerNodeAddressContainersUnauthorized() *GetProvisionerNodeAddressContainersUnauthorized {
	return &GetProvisionerNodeAddressContainersUnauthorized{}
}

/*GetProvisionerNodeAddressContainersUnauthorized handles this case with default header values.

Unauthorized
*/
type GetProvisionerNodeAddressContainersUnauthorized struct {
}

func (o *GetProvisionerNodeAddressContainersUnauthorized) Error() string {
	return fmt.Sprintf("[GET /{provisioner}/node/{address}/containers][%d] getProvisionerNodeAddressContainersUnauthorized ", 401)
}

func (o *GetProvisionerNodeAddressContainersUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetProvisionerNodeAddressContainersNotFound creates a GetProvisionerNodeAddressContainersNotFound with default headers values
func NewGetProvisionerNodeAddressContainersNotFound() *GetProvisionerNodeAddressContainersNotFound {
	return &GetProvisionerNodeAddressContainersNotFound{}
}

/*GetProvisionerNodeAddressContainersNotFound handles this case with default header values.

Not found
*/
type GetProvisionerNodeAddressContainersNotFound struct {
}

func (o *GetProvisionerNodeAddressContainersNotFound) Error() string {
	return fmt.Sprintf("[GET /{provisioner}/node/{address}/containers][%d] getProvisionerNodeAddressContainersNotFound ", 404)
}

func (o *GetProvisionerNodeAddressContainersNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
