// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetServicesServicePlansParams creates a new GetServicesServicePlansParams object
// with the default values initialized.
func NewGetServicesServicePlansParams() *GetServicesServicePlansParams {
	var ()
	return &GetServicesServicePlansParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetServicesServicePlansParamsWithTimeout creates a new GetServicesServicePlansParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetServicesServicePlansParamsWithTimeout(timeout time.Duration) *GetServicesServicePlansParams {
	var ()
	return &GetServicesServicePlansParams{

		timeout: timeout,
	}
}

// NewGetServicesServicePlansParamsWithContext creates a new GetServicesServicePlansParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetServicesServicePlansParamsWithContext(ctx context.Context) *GetServicesServicePlansParams {
	var ()
	return &GetServicesServicePlansParams{

		Context: ctx,
	}
}

// NewGetServicesServicePlansParamsWithHTTPClient creates a new GetServicesServicePlansParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetServicesServicePlansParamsWithHTTPClient(client *http.Client) *GetServicesServicePlansParams {
	var ()
	return &GetServicesServicePlansParams{
		HTTPClient: client,
	}
}

/*GetServicesServicePlansParams contains all the parameters to send to the API endpoint
for the get services service plans operation typically these are written to a http.Request
*/
type GetServicesServicePlansParams struct {

	/*Service
	  Service name.

	*/
	Service string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get services service plans params
func (o *GetServicesServicePlansParams) WithTimeout(timeout time.Duration) *GetServicesServicePlansParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get services service plans params
func (o *GetServicesServicePlansParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get services service plans params
func (o *GetServicesServicePlansParams) WithContext(ctx context.Context) *GetServicesServicePlansParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get services service plans params
func (o *GetServicesServicePlansParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get services service plans params
func (o *GetServicesServicePlansParams) WithHTTPClient(client *http.Client) *GetServicesServicePlansParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get services service plans params
func (o *GetServicesServicePlansParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithService adds the service to the get services service plans params
func (o *GetServicesServicePlansParams) WithService(service string) *GetServicesServicePlansParams {
	o.SetService(service)
	return o
}

// SetService adds the service to the get services service plans params
func (o *GetServicesServicePlansParams) SetService(service string) {
	o.Service = service
}

// WriteToRequest writes these params to a swagger request
func (o *GetServicesServicePlansParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param service
	if err := r.SetPathParam("service", o.Service); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
