// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// GetRoutersReader is a Reader for the GetRouters structure.
type GetRoutersReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetRoutersReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetRoutersOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 204:
		result := NewGetRoutersNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetRoutersOK creates a GetRoutersOK with default headers values
func NewGetRoutersOK() *GetRoutersOK {
	return &GetRoutersOK{}
}

/*GetRoutersOK handles this case with default header values.

OK
*/
type GetRoutersOK struct {
}

func (o *GetRoutersOK) Error() string {
	return fmt.Sprintf("[GET /routers][%d] getRoutersOK ", 200)
}

func (o *GetRoutersOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetRoutersNoContent creates a GetRoutersNoContent with default headers values
func NewGetRoutersNoContent() *GetRoutersNoContent {
	return &GetRoutersNoContent{}
}

/*GetRoutersNoContent handles this case with default header values.

No content
*/
type GetRoutersNoContent struct {
}

func (o *GetRoutersNoContent) Error() string {
	return fmt.Sprintf("[GET /routers][%d] getRoutersNoContent ", 204)
}

func (o *GetRoutersNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
