// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// GetAutoscaleConfigReader is a Reader for the GetAutoscaleConfig structure.
type GetAutoscaleConfigReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAutoscaleConfigReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetAutoscaleConfigOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 401:
		result := NewGetAutoscaleConfigUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetAutoscaleConfigOK creates a GetAutoscaleConfigOK with default headers values
func NewGetAutoscaleConfigOK() *GetAutoscaleConfigOK {
	return &GetAutoscaleConfigOK{}
}

/*GetAutoscaleConfigOK handles this case with default header values.

Ok
*/
type GetAutoscaleConfigOK struct {
}

func (o *GetAutoscaleConfigOK) Error() string {
	return fmt.Sprintf("[GET /autoscale/config][%d] getAutoscaleConfigOK ", 200)
}

func (o *GetAutoscaleConfigOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetAutoscaleConfigUnauthorized creates a GetAutoscaleConfigUnauthorized with default headers values
func NewGetAutoscaleConfigUnauthorized() *GetAutoscaleConfigUnauthorized {
	return &GetAutoscaleConfigUnauthorized{}
}

/*GetAutoscaleConfigUnauthorized handles this case with default header values.

Unauthorized
*/
type GetAutoscaleConfigUnauthorized struct {
}

func (o *GetAutoscaleConfigUnauthorized) Error() string {
	return fmt.Sprintf("[GET /autoscale/config][%d] getAutoscaleConfigUnauthorized ", 401)
}

func (o *GetAutoscaleConfigUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
