// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetServicesServiceInstancesInstanceStatusParams creates a new GetServicesServiceInstancesInstanceStatusParams object
// with the default values initialized.
func NewGetServicesServiceInstancesInstanceStatusParams() *GetServicesServiceInstancesInstanceStatusParams {
	var ()
	return &GetServicesServiceInstancesInstanceStatusParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetServicesServiceInstancesInstanceStatusParamsWithTimeout creates a new GetServicesServiceInstancesInstanceStatusParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetServicesServiceInstancesInstanceStatusParamsWithTimeout(timeout time.Duration) *GetServicesServiceInstancesInstanceStatusParams {
	var ()
	return &GetServicesServiceInstancesInstanceStatusParams{

		timeout: timeout,
	}
}

// NewGetServicesServiceInstancesInstanceStatusParamsWithContext creates a new GetServicesServiceInstancesInstanceStatusParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetServicesServiceInstancesInstanceStatusParamsWithContext(ctx context.Context) *GetServicesServiceInstancesInstanceStatusParams {
	var ()
	return &GetServicesServiceInstancesInstanceStatusParams{

		Context: ctx,
	}
}

// NewGetServicesServiceInstancesInstanceStatusParamsWithHTTPClient creates a new GetServicesServiceInstancesInstanceStatusParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetServicesServiceInstancesInstanceStatusParamsWithHTTPClient(client *http.Client) *GetServicesServiceInstancesInstanceStatusParams {
	var ()
	return &GetServicesServiceInstancesInstanceStatusParams{
		HTTPClient: client,
	}
}

/*GetServicesServiceInstancesInstanceStatusParams contains all the parameters to send to the API endpoint
for the get services service instances instance status operation typically these are written to a http.Request
*/
type GetServicesServiceInstancesInstanceStatusParams struct {

	/*Instance
	  Instance name.

	*/
	Instance string
	/*Service
	  Service name.

	*/
	Service string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get services service instances instance status params
func (o *GetServicesServiceInstancesInstanceStatusParams) WithTimeout(timeout time.Duration) *GetServicesServiceInstancesInstanceStatusParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get services service instances instance status params
func (o *GetServicesServiceInstancesInstanceStatusParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get services service instances instance status params
func (o *GetServicesServiceInstancesInstanceStatusParams) WithContext(ctx context.Context) *GetServicesServiceInstancesInstanceStatusParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get services service instances instance status params
func (o *GetServicesServiceInstancesInstanceStatusParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get services service instances instance status params
func (o *GetServicesServiceInstancesInstanceStatusParams) WithHTTPClient(client *http.Client) *GetServicesServiceInstancesInstanceStatusParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get services service instances instance status params
func (o *GetServicesServiceInstancesInstanceStatusParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithInstance adds the instance to the get services service instances instance status params
func (o *GetServicesServiceInstancesInstanceStatusParams) WithInstance(instance string) *GetServicesServiceInstancesInstanceStatusParams {
	o.SetInstance(instance)
	return o
}

// SetInstance adds the instance to the get services service instances instance status params
func (o *GetServicesServiceInstancesInstanceStatusParams) SetInstance(instance string) {
	o.Instance = instance
}

// WithService adds the service to the get services service instances instance status params
func (o *GetServicesServiceInstancesInstanceStatusParams) WithService(service string) *GetServicesServiceInstancesInstanceStatusParams {
	o.SetService(service)
	return o
}

// SetService adds the service to the get services service instances instance status params
func (o *GetServicesServiceInstancesInstanceStatusParams) SetService(service string) {
	o.Service = service
}

// WriteToRequest writes these params to a swagger request
func (o *GetServicesServiceInstancesInstanceStatusParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param instance
	if err := r.SetPathParam("instance", o.Instance); err != nil {
		return err
	}

	// path param service
	if err := r.SetPathParam("service", o.Service); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
