// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetAppAppRoutersParams creates a new GetAppAppRoutersParams object
// with the default values initialized.
func NewGetAppAppRoutersParams() *GetAppAppRoutersParams {
	var ()
	return &GetAppAppRoutersParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetAppAppRoutersParamsWithTimeout creates a new GetAppAppRoutersParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetAppAppRoutersParamsWithTimeout(timeout time.Duration) *GetAppAppRoutersParams {
	var ()
	return &GetAppAppRoutersParams{

		timeout: timeout,
	}
}

// NewGetAppAppRoutersParamsWithContext creates a new GetAppAppRoutersParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetAppAppRoutersParamsWithContext(ctx context.Context) *GetAppAppRoutersParams {
	var ()
	return &GetAppAppRoutersParams{

		Context: ctx,
	}
}

// NewGetAppAppRoutersParamsWithHTTPClient creates a new GetAppAppRoutersParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetAppAppRoutersParamsWithHTTPClient(client *http.Client) *GetAppAppRoutersParams {
	var ()
	return &GetAppAppRoutersParams{
		HTTPClient: client,
	}
}

/*GetAppAppRoutersParams contains all the parameters to send to the API endpoint
for the get app app routers operation typically these are written to a http.Request
*/
type GetAppAppRoutersParams struct {

	/*App
	  App name.

	*/
	App string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get app app routers params
func (o *GetAppAppRoutersParams) WithTimeout(timeout time.Duration) *GetAppAppRoutersParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get app app routers params
func (o *GetAppAppRoutersParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get app app routers params
func (o *GetAppAppRoutersParams) WithContext(ctx context.Context) *GetAppAppRoutersParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get app app routers params
func (o *GetAppAppRoutersParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get app app routers params
func (o *GetAppAppRoutersParams) WithHTTPClient(client *http.Client) *GetAppAppRoutersParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get app app routers params
func (o *GetAppAppRoutersParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithApp adds the app to the get app app routers params
func (o *GetAppAppRoutersParams) WithApp(app string) *GetAppAppRoutersParams {
	o.SetApp(app)
	return o
}

// SetApp adds the app to the get app app routers params
func (o *GetAppAppRoutersParams) SetApp(app string) {
	o.App = app
}

// WriteToRequest writes these params to a swagger request
func (o *GetAppAppRoutersParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param app
	if err := r.SetPathParam("app", o.App); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
