// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// PostAutoscaleRulesReader is a Reader for the PostAutoscaleRules structure.
type PostAutoscaleRulesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostAutoscaleRulesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewPostAutoscaleRulesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewPostAutoscaleRulesBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 401:
		result := NewPostAutoscaleRulesUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPostAutoscaleRulesOK creates a PostAutoscaleRulesOK with default headers values
func NewPostAutoscaleRulesOK() *PostAutoscaleRulesOK {
	return &PostAutoscaleRulesOK{}
}

/*PostAutoscaleRulesOK handles this case with default header values.

Ok
*/
type PostAutoscaleRulesOK struct {
}

func (o *PostAutoscaleRulesOK) Error() string {
	return fmt.Sprintf("[POST /autoscale/rules][%d] postAutoscaleRulesOK ", 200)
}

func (o *PostAutoscaleRulesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPostAutoscaleRulesBadRequest creates a PostAutoscaleRulesBadRequest with default headers values
func NewPostAutoscaleRulesBadRequest() *PostAutoscaleRulesBadRequest {
	return &PostAutoscaleRulesBadRequest{}
}

/*PostAutoscaleRulesBadRequest handles this case with default header values.

Invalid data
*/
type PostAutoscaleRulesBadRequest struct {
}

func (o *PostAutoscaleRulesBadRequest) Error() string {
	return fmt.Sprintf("[POST /autoscale/rules][%d] postAutoscaleRulesBadRequest ", 400)
}

func (o *PostAutoscaleRulesBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPostAutoscaleRulesUnauthorized creates a PostAutoscaleRulesUnauthorized with default headers values
func NewPostAutoscaleRulesUnauthorized() *PostAutoscaleRulesUnauthorized {
	return &PostAutoscaleRulesUnauthorized{}
}

/*PostAutoscaleRulesUnauthorized handles this case with default header values.

Unauthorized
*/
type PostAutoscaleRulesUnauthorized struct {
}

func (o *PostAutoscaleRulesUnauthorized) Error() string {
	return fmt.Sprintf("[POST /autoscale/rules][%d] postAutoscaleRulesUnauthorized ", 401)
}

func (o *PostAutoscaleRulesUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
