// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewPostAppsAppnameDeployRebuildParams creates a new PostAppsAppnameDeployRebuildParams object
// with the default values initialized.
func NewPostAppsAppnameDeployRebuildParams() *PostAppsAppnameDeployRebuildParams {

	return &PostAppsAppnameDeployRebuildParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPostAppsAppnameDeployRebuildParamsWithTimeout creates a new PostAppsAppnameDeployRebuildParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPostAppsAppnameDeployRebuildParamsWithTimeout(timeout time.Duration) *PostAppsAppnameDeployRebuildParams {

	return &PostAppsAppnameDeployRebuildParams{

		timeout: timeout,
	}
}

// NewPostAppsAppnameDeployRebuildParamsWithContext creates a new PostAppsAppnameDeployRebuildParams object
// with the default values initialized, and the ability to set a context for a request
func NewPostAppsAppnameDeployRebuildParamsWithContext(ctx context.Context) *PostAppsAppnameDeployRebuildParams {

	return &PostAppsAppnameDeployRebuildParams{

		Context: ctx,
	}
}

// NewPostAppsAppnameDeployRebuildParamsWithHTTPClient creates a new PostAppsAppnameDeployRebuildParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPostAppsAppnameDeployRebuildParamsWithHTTPClient(client *http.Client) *PostAppsAppnameDeployRebuildParams {

	return &PostAppsAppnameDeployRebuildParams{
		HTTPClient: client,
	}
}

/*PostAppsAppnameDeployRebuildParams contains all the parameters to send to the API endpoint
for the post apps appname deploy rebuild operation typically these are written to a http.Request
*/
type PostAppsAppnameDeployRebuildParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the post apps appname deploy rebuild params
func (o *PostAppsAppnameDeployRebuildParams) WithTimeout(timeout time.Duration) *PostAppsAppnameDeployRebuildParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post apps appname deploy rebuild params
func (o *PostAppsAppnameDeployRebuildParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post apps appname deploy rebuild params
func (o *PostAppsAppnameDeployRebuildParams) WithContext(ctx context.Context) *PostAppsAppnameDeployRebuildParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post apps appname deploy rebuild params
func (o *PostAppsAppnameDeployRebuildParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post apps appname deploy rebuild params
func (o *PostAppsAppnameDeployRebuildParams) WithHTTPClient(client *http.Client) *PostAppsAppnameDeployRebuildParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post apps appname deploy rebuild params
func (o *PostAppsAppnameDeployRebuildParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *PostAppsAppnameDeployRebuildParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
