// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewPostAppsAppDeployRebuildParams creates a new PostAppsAppDeployRebuildParams object
// with the default values initialized.
func NewPostAppsAppDeployRebuildParams() *PostAppsAppDeployRebuildParams {
	var ()
	return &PostAppsAppDeployRebuildParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPostAppsAppDeployRebuildParamsWithTimeout creates a new PostAppsAppDeployRebuildParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPostAppsAppDeployRebuildParamsWithTimeout(timeout time.Duration) *PostAppsAppDeployRebuildParams {
	var ()
	return &PostAppsAppDeployRebuildParams{

		timeout: timeout,
	}
}

// NewPostAppsAppDeployRebuildParamsWithContext creates a new PostAppsAppDeployRebuildParams object
// with the default values initialized, and the ability to set a context for a request
func NewPostAppsAppDeployRebuildParamsWithContext(ctx context.Context) *PostAppsAppDeployRebuildParams {
	var ()
	return &PostAppsAppDeployRebuildParams{

		Context: ctx,
	}
}

// NewPostAppsAppDeployRebuildParamsWithHTTPClient creates a new PostAppsAppDeployRebuildParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPostAppsAppDeployRebuildParamsWithHTTPClient(client *http.Client) *PostAppsAppDeployRebuildParams {
	var ()
	return &PostAppsAppDeployRebuildParams{
		HTTPClient: client,
	}
}

/*PostAppsAppDeployRebuildParams contains all the parameters to send to the API endpoint
for the post apps app deploy rebuild operation typically these are written to a http.Request
*/
type PostAppsAppDeployRebuildParams struct {

	/*App
	  App name.

	*/
	App string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the post apps app deploy rebuild params
func (o *PostAppsAppDeployRebuildParams) WithTimeout(timeout time.Duration) *PostAppsAppDeployRebuildParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post apps app deploy rebuild params
func (o *PostAppsAppDeployRebuildParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post apps app deploy rebuild params
func (o *PostAppsAppDeployRebuildParams) WithContext(ctx context.Context) *PostAppsAppDeployRebuildParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post apps app deploy rebuild params
func (o *PostAppsAppDeployRebuildParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post apps app deploy rebuild params
func (o *PostAppsAppDeployRebuildParams) WithHTTPClient(client *http.Client) *PostAppsAppDeployRebuildParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post apps app deploy rebuild params
func (o *PostAppsAppDeployRebuildParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithApp adds the app to the post apps app deploy rebuild params
func (o *PostAppsAppDeployRebuildParams) WithApp(app string) *PostAppsAppDeployRebuildParams {
	o.SetApp(app)
	return o
}

// SetApp adds the app to the post apps app deploy rebuild params
func (o *PostAppsAppDeployRebuildParams) SetApp(app string) {
	o.App = app
}

// WriteToRequest writes these params to a swagger request
func (o *PostAppsAppDeployRebuildParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param app
	if err := r.SetPathParam("app", o.App); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
