// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewPostRolesRolePermissionsParams creates a new PostRolesRolePermissionsParams object
// with the default values initialized.
func NewPostRolesRolePermissionsParams() *PostRolesRolePermissionsParams {
	var ()
	return &PostRolesRolePermissionsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPostRolesRolePermissionsParamsWithTimeout creates a new PostRolesRolePermissionsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPostRolesRolePermissionsParamsWithTimeout(timeout time.Duration) *PostRolesRolePermissionsParams {
	var ()
	return &PostRolesRolePermissionsParams{

		timeout: timeout,
	}
}

// NewPostRolesRolePermissionsParamsWithContext creates a new PostRolesRolePermissionsParams object
// with the default values initialized, and the ability to set a context for a request
func NewPostRolesRolePermissionsParamsWithContext(ctx context.Context) *PostRolesRolePermissionsParams {
	var ()
	return &PostRolesRolePermissionsParams{

		Context: ctx,
	}
}

// NewPostRolesRolePermissionsParamsWithHTTPClient creates a new PostRolesRolePermissionsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPostRolesRolePermissionsParamsWithHTTPClient(client *http.Client) *PostRolesRolePermissionsParams {
	var ()
	return &PostRolesRolePermissionsParams{
		HTTPClient: client,
	}
}

/*PostRolesRolePermissionsParams contains all the parameters to send to the API endpoint
for the post roles role permissions operation typically these are written to a http.Request
*/
type PostRolesRolePermissionsParams struct {

	/*Role
	  Role name.

	*/
	Role string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the post roles role permissions params
func (o *PostRolesRolePermissionsParams) WithTimeout(timeout time.Duration) *PostRolesRolePermissionsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post roles role permissions params
func (o *PostRolesRolePermissionsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post roles role permissions params
func (o *PostRolesRolePermissionsParams) WithContext(ctx context.Context) *PostRolesRolePermissionsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post roles role permissions params
func (o *PostRolesRolePermissionsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post roles role permissions params
func (o *PostRolesRolePermissionsParams) WithHTTPClient(client *http.Client) *PostRolesRolePermissionsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post roles role permissions params
func (o *PostRolesRolePermissionsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithRole adds the role to the post roles role permissions params
func (o *PostRolesRolePermissionsParams) WithRole(role string) *PostRolesRolePermissionsParams {
	o.SetRole(role)
	return o
}

// SetRole adds the role to the post roles role permissions params
func (o *PostRolesRolePermissionsParams) SetRole(role string) {
	o.Role = role
}

// WriteToRequest writes these params to a swagger request
func (o *PostRolesRolePermissionsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param role
	if err := r.SetPathParam("role", o.Role); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
