// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewPostAppsAppRestartParams creates a new PostAppsAppRestartParams object
// with the default values initialized.
func NewPostAppsAppRestartParams() *PostAppsAppRestartParams {
	var ()
	return &PostAppsAppRestartParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPostAppsAppRestartParamsWithTimeout creates a new PostAppsAppRestartParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPostAppsAppRestartParamsWithTimeout(timeout time.Duration) *PostAppsAppRestartParams {
	var ()
	return &PostAppsAppRestartParams{

		timeout: timeout,
	}
}

// NewPostAppsAppRestartParamsWithContext creates a new PostAppsAppRestartParams object
// with the default values initialized, and the ability to set a context for a request
func NewPostAppsAppRestartParamsWithContext(ctx context.Context) *PostAppsAppRestartParams {
	var ()
	return &PostAppsAppRestartParams{

		Context: ctx,
	}
}

// NewPostAppsAppRestartParamsWithHTTPClient creates a new PostAppsAppRestartParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPostAppsAppRestartParamsWithHTTPClient(client *http.Client) *PostAppsAppRestartParams {
	var ()
	return &PostAppsAppRestartParams{
		HTTPClient: client,
	}
}

/*PostAppsAppRestartParams contains all the parameters to send to the API endpoint
for the post apps app restart operation typically these are written to a http.Request
*/
type PostAppsAppRestartParams struct {

	/*App
	  App name.

	*/
	App string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the post apps app restart params
func (o *PostAppsAppRestartParams) WithTimeout(timeout time.Duration) *PostAppsAppRestartParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post apps app restart params
func (o *PostAppsAppRestartParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post apps app restart params
func (o *PostAppsAppRestartParams) WithContext(ctx context.Context) *PostAppsAppRestartParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post apps app restart params
func (o *PostAppsAppRestartParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post apps app restart params
func (o *PostAppsAppRestartParams) WithHTTPClient(client *http.Client) *PostAppsAppRestartParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post apps app restart params
func (o *PostAppsAppRestartParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithApp adds the app to the post apps app restart params
func (o *PostAppsAppRestartParams) WithApp(app string) *PostAppsAppRestartParams {
	o.SetApp(app)
	return o
}

// SetApp adds the app to the post apps app restart params
func (o *PostAppsAppRestartParams) SetApp(app string) {
	o.App = app
}

// WriteToRequest writes these params to a swagger request
func (o *PostAppsAppRestartParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param app
	if err := r.SetPathParam("app", o.App); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
