// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// PostAppsAppRestartReader is a Reader for the PostAppsAppRestart structure.
type PostAppsAppRestartReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostAppsAppRestartReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewPostAppsAppRestartOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 401:
		result := NewPostAppsAppRestartUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 404:
		result := NewPostAppsAppRestartNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPostAppsAppRestartOK creates a PostAppsAppRestartOK with default headers values
func NewPostAppsAppRestartOK() *PostAppsAppRestartOK {
	return &PostAppsAppRestartOK{}
}

/*PostAppsAppRestartOK handles this case with default header values.

Ok
*/
type PostAppsAppRestartOK struct {
}

func (o *PostAppsAppRestartOK) Error() string {
	return fmt.Sprintf("[POST /apps/{app}/restart][%d] postAppsAppRestartOK ", 200)
}

func (o *PostAppsAppRestartOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPostAppsAppRestartUnauthorized creates a PostAppsAppRestartUnauthorized with default headers values
func NewPostAppsAppRestartUnauthorized() *PostAppsAppRestartUnauthorized {
	return &PostAppsAppRestartUnauthorized{}
}

/*PostAppsAppRestartUnauthorized handles this case with default header values.

Unauthorized
*/
type PostAppsAppRestartUnauthorized struct {
}

func (o *PostAppsAppRestartUnauthorized) Error() string {
	return fmt.Sprintf("[POST /apps/{app}/restart][%d] postAppsAppRestartUnauthorized ", 401)
}

func (o *PostAppsAppRestartUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPostAppsAppRestartNotFound creates a PostAppsAppRestartNotFound with default headers values
func NewPostAppsAppRestartNotFound() *PostAppsAppRestartNotFound {
	return &PostAppsAppRestartNotFound{}
}

/*PostAppsAppRestartNotFound handles this case with default header values.

App not found
*/
type PostAppsAppRestartNotFound struct {
}

func (o *PostAppsAppRestartNotFound) Error() string {
	return fmt.Sprintf("[POST /apps/{app}/restart][%d] postAppsAppRestartNotFound ", 404)
}

func (o *PostAppsAppRestartNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
