// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// PostAppsAppUnitsUnitReader is a Reader for the PostAppsAppUnitsUnit structure.
type PostAppsAppUnitsUnitReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostAppsAppUnitsUnitReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewPostAppsAppUnitsUnitOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewPostAppsAppUnitsUnitBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 401:
		result := NewPostAppsAppUnitsUnitUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 404:
		result := NewPostAppsAppUnitsUnitNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPostAppsAppUnitsUnitOK creates a PostAppsAppUnitsUnitOK with default headers values
func NewPostAppsAppUnitsUnitOK() *PostAppsAppUnitsUnitOK {
	return &PostAppsAppUnitsUnitOK{}
}

/*PostAppsAppUnitsUnitOK handles this case with default header values.

Ok
*/
type PostAppsAppUnitsUnitOK struct {
}

func (o *PostAppsAppUnitsUnitOK) Error() string {
	return fmt.Sprintf("[POST /apps/{app}/units/{unit}][%d] postAppsAppUnitsUnitOK ", 200)
}

func (o *PostAppsAppUnitsUnitOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPostAppsAppUnitsUnitBadRequest creates a PostAppsAppUnitsUnitBadRequest with default headers values
func NewPostAppsAppUnitsUnitBadRequest() *PostAppsAppUnitsUnitBadRequest {
	return &PostAppsAppUnitsUnitBadRequest{}
}

/*PostAppsAppUnitsUnitBadRequest handles this case with default header values.

Invalid data
*/
type PostAppsAppUnitsUnitBadRequest struct {
}

func (o *PostAppsAppUnitsUnitBadRequest) Error() string {
	return fmt.Sprintf("[POST /apps/{app}/units/{unit}][%d] postAppsAppUnitsUnitBadRequest ", 400)
}

func (o *PostAppsAppUnitsUnitBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPostAppsAppUnitsUnitUnauthorized creates a PostAppsAppUnitsUnitUnauthorized with default headers values
func NewPostAppsAppUnitsUnitUnauthorized() *PostAppsAppUnitsUnitUnauthorized {
	return &PostAppsAppUnitsUnitUnauthorized{}
}

/*PostAppsAppUnitsUnitUnauthorized handles this case with default header values.

Unauthorized
*/
type PostAppsAppUnitsUnitUnauthorized struct {
}

func (o *PostAppsAppUnitsUnitUnauthorized) Error() string {
	return fmt.Sprintf("[POST /apps/{app}/units/{unit}][%d] postAppsAppUnitsUnitUnauthorized ", 401)
}

func (o *PostAppsAppUnitsUnitUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPostAppsAppUnitsUnitNotFound creates a PostAppsAppUnitsUnitNotFound with default headers values
func NewPostAppsAppUnitsUnitNotFound() *PostAppsAppUnitsUnitNotFound {
	return &PostAppsAppUnitsUnitNotFound{}
}

/*PostAppsAppUnitsUnitNotFound handles this case with default header values.

App or unit not found
*/
type PostAppsAppUnitsUnitNotFound struct {
}

func (o *PostAppsAppUnitsUnitNotFound) Error() string {
	return fmt.Sprintf("[POST /apps/{app}/units/{unit}][%d] postAppsAppUnitsUnitNotFound ", 404)
}

func (o *PostAppsAppUnitsUnitNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
