// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// PostAppsAppLogReader is a Reader for the PostAppsAppLog structure.
type PostAppsAppLogReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostAppsAppLogReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewPostAppsAppLogOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewPostAppsAppLogBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 401:
		result := NewPostAppsAppLogUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 404:
		result := NewPostAppsAppLogNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPostAppsAppLogOK creates a PostAppsAppLogOK with default headers values
func NewPostAppsAppLogOK() *PostAppsAppLogOK {
	return &PostAppsAppLogOK{}
}

/*PostAppsAppLogOK handles this case with default header values.

Ok
*/
type PostAppsAppLogOK struct {
}

func (o *PostAppsAppLogOK) Error() string {
	return fmt.Sprintf("[POST /apps/{app}/log][%d] postAppsAppLogOK ", 200)
}

func (o *PostAppsAppLogOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPostAppsAppLogBadRequest creates a PostAppsAppLogBadRequest with default headers values
func NewPostAppsAppLogBadRequest() *PostAppsAppLogBadRequest {
	return &PostAppsAppLogBadRequest{}
}

/*PostAppsAppLogBadRequest handles this case with default header values.

Invalid data
*/
type PostAppsAppLogBadRequest struct {
}

func (o *PostAppsAppLogBadRequest) Error() string {
	return fmt.Sprintf("[POST /apps/{app}/log][%d] postAppsAppLogBadRequest ", 400)
}

func (o *PostAppsAppLogBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPostAppsAppLogUnauthorized creates a PostAppsAppLogUnauthorized with default headers values
func NewPostAppsAppLogUnauthorized() *PostAppsAppLogUnauthorized {
	return &PostAppsAppLogUnauthorized{}
}

/*PostAppsAppLogUnauthorized handles this case with default header values.

Unauthorized
*/
type PostAppsAppLogUnauthorized struct {
}

func (o *PostAppsAppLogUnauthorized) Error() string {
	return fmt.Sprintf("[POST /apps/{app}/log][%d] postAppsAppLogUnauthorized ", 401)
}

func (o *PostAppsAppLogUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPostAppsAppLogNotFound creates a PostAppsAppLogNotFound with default headers values
func NewPostAppsAppLogNotFound() *PostAppsAppLogNotFound {
	return &PostAppsAppLogNotFound{}
}

/*PostAppsAppLogNotFound handles this case with default header values.

App not found
*/
type PostAppsAppLogNotFound struct {
}

func (o *PostAppsAppLogNotFound) Error() string {
	return fmt.Sprintf("[POST /apps/{app}/log][%d] postAppsAppLogNotFound ", 404)
}

func (o *PostAppsAppLogNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
