// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewPostAppsAppnameDiffParams creates a new PostAppsAppnameDiffParams object
// with the default values initialized.
func NewPostAppsAppnameDiffParams() *PostAppsAppnameDiffParams {

	return &PostAppsAppnameDiffParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPostAppsAppnameDiffParamsWithTimeout creates a new PostAppsAppnameDiffParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPostAppsAppnameDiffParamsWithTimeout(timeout time.Duration) *PostAppsAppnameDiffParams {

	return &PostAppsAppnameDiffParams{

		timeout: timeout,
	}
}

// NewPostAppsAppnameDiffParamsWithContext creates a new PostAppsAppnameDiffParams object
// with the default values initialized, and the ability to set a context for a request
func NewPostAppsAppnameDiffParamsWithContext(ctx context.Context) *PostAppsAppnameDiffParams {

	return &PostAppsAppnameDiffParams{

		Context: ctx,
	}
}

// NewPostAppsAppnameDiffParamsWithHTTPClient creates a new PostAppsAppnameDiffParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPostAppsAppnameDiffParamsWithHTTPClient(client *http.Client) *PostAppsAppnameDiffParams {

	return &PostAppsAppnameDiffParams{
		HTTPClient: client,
	}
}

/*PostAppsAppnameDiffParams contains all the parameters to send to the API endpoint
for the post apps appname diff operation typically these are written to a http.Request
*/
type PostAppsAppnameDiffParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the post apps appname diff params
func (o *PostAppsAppnameDiffParams) WithTimeout(timeout time.Duration) *PostAppsAppnameDiffParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post apps appname diff params
func (o *PostAppsAppnameDiffParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post apps appname diff params
func (o *PostAppsAppnameDiffParams) WithContext(ctx context.Context) *PostAppsAppnameDiffParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post apps appname diff params
func (o *PostAppsAppnameDiffParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post apps appname diff params
func (o *PostAppsAppnameDiffParams) WithHTTPClient(client *http.Client) *PostAppsAppnameDiffParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post apps appname diff params
func (o *PostAppsAppnameDiffParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *PostAppsAppnameDiffParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
