// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// PostRolesRolePermissionsReader is a Reader for the PostRolesRolePermissions structure.
type PostRolesRolePermissionsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostRolesRolePermissionsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewPostRolesRolePermissionsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewPostRolesRolePermissionsBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 401:
		result := NewPostRolesRolePermissionsUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 409:
		result := NewPostRolesRolePermissionsConflict()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPostRolesRolePermissionsOK creates a PostRolesRolePermissionsOK with default headers values
func NewPostRolesRolePermissionsOK() *PostRolesRolePermissionsOK {
	return &PostRolesRolePermissionsOK{}
}

/*PostRolesRolePermissionsOK handles this case with default header values.

Ok
*/
type PostRolesRolePermissionsOK struct {
}

func (o *PostRolesRolePermissionsOK) Error() string {
	return fmt.Sprintf("[POST /roles/{role}/permissions][%d] postRolesRolePermissionsOK ", 200)
}

func (o *PostRolesRolePermissionsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPostRolesRolePermissionsBadRequest creates a PostRolesRolePermissionsBadRequest with default headers values
func NewPostRolesRolePermissionsBadRequest() *PostRolesRolePermissionsBadRequest {
	return &PostRolesRolePermissionsBadRequest{}
}

/*PostRolesRolePermissionsBadRequest handles this case with default header values.

Invalid data
*/
type PostRolesRolePermissionsBadRequest struct {
}

func (o *PostRolesRolePermissionsBadRequest) Error() string {
	return fmt.Sprintf("[POST /roles/{role}/permissions][%d] postRolesRolePermissionsBadRequest ", 400)
}

func (o *PostRolesRolePermissionsBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPostRolesRolePermissionsUnauthorized creates a PostRolesRolePermissionsUnauthorized with default headers values
func NewPostRolesRolePermissionsUnauthorized() *PostRolesRolePermissionsUnauthorized {
	return &PostRolesRolePermissionsUnauthorized{}
}

/*PostRolesRolePermissionsUnauthorized handles this case with default header values.

Unauthorized
*/
type PostRolesRolePermissionsUnauthorized struct {
}

func (o *PostRolesRolePermissionsUnauthorized) Error() string {
	return fmt.Sprintf("[POST /roles/{role}/permissions][%d] postRolesRolePermissionsUnauthorized ", 401)
}

func (o *PostRolesRolePermissionsUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPostRolesRolePermissionsConflict creates a PostRolesRolePermissionsConflict with default headers values
func NewPostRolesRolePermissionsConflict() *PostRolesRolePermissionsConflict {
	return &PostRolesRolePermissionsConflict{}
}

/*PostRolesRolePermissionsConflict handles this case with default header values.

Permission not allowed
*/
type PostRolesRolePermissionsConflict struct {
}

func (o *PostRolesRolePermissionsConflict) Error() string {
	return fmt.Sprintf("[POST /roles/{role}/permissions][%d] postRolesRolePermissionsConflict ", 409)
}

func (o *PostRolesRolePermissionsConflict) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
