// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// PostNodeReader is a Reader for the PostNode structure.
type PostNodeReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostNodeReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 201:
		result := NewPostNodeCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 401:
		result := NewPostNodeUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 404:
		result := NewPostNodeNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPostNodeCreated creates a PostNodeCreated with default headers values
func NewPostNodeCreated() *PostNodeCreated {
	return &PostNodeCreated{}
}

/*PostNodeCreated handles this case with default header values.

Ok
*/
type PostNodeCreated struct {
}

func (o *PostNodeCreated) Error() string {
	return fmt.Sprintf("[POST /node][%d] postNodeCreated ", 201)
}

func (o *PostNodeCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPostNodeUnauthorized creates a PostNodeUnauthorized with default headers values
func NewPostNodeUnauthorized() *PostNodeUnauthorized {
	return &PostNodeUnauthorized{}
}

/*PostNodeUnauthorized handles this case with default header values.

Unauthorized
*/
type PostNodeUnauthorized struct {
}

func (o *PostNodeUnauthorized) Error() string {
	return fmt.Sprintf("[POST /node][%d] postNodeUnauthorized ", 401)
}

func (o *PostNodeUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPostNodeNotFound creates a PostNodeNotFound with default headers values
func NewPostNodeNotFound() *PostNodeNotFound {
	return &PostNodeNotFound{}
}

/*PostNodeNotFound handles this case with default header values.

Not found
*/
type PostNodeNotFound struct {
}

func (o *PostNodeNotFound) Error() string {
	return fmt.Sprintf("[POST /node][%d] postNodeNotFound ", 404)
}

func (o *PostNodeNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
