// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// PostAppsAppDeployRollbackReader is a Reader for the PostAppsAppDeployRollback structure.
type PostAppsAppDeployRollbackReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostAppsAppDeployRollbackReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewPostAppsAppDeployRollbackOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewPostAppsAppDeployRollbackBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 403:
		result := NewPostAppsAppDeployRollbackForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 404:
		result := NewPostAppsAppDeployRollbackNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPostAppsAppDeployRollbackOK creates a PostAppsAppDeployRollbackOK with default headers values
func NewPostAppsAppDeployRollbackOK() *PostAppsAppDeployRollbackOK {
	return &PostAppsAppDeployRollbackOK{}
}

/*PostAppsAppDeployRollbackOK handles this case with default header values.

OK
*/
type PostAppsAppDeployRollbackOK struct {
}

func (o *PostAppsAppDeployRollbackOK) Error() string {
	return fmt.Sprintf("[POST /apps/{app}/deploy/rollback][%d] postAppsAppDeployRollbackOK ", 200)
}

func (o *PostAppsAppDeployRollbackOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPostAppsAppDeployRollbackBadRequest creates a PostAppsAppDeployRollbackBadRequest with default headers values
func NewPostAppsAppDeployRollbackBadRequest() *PostAppsAppDeployRollbackBadRequest {
	return &PostAppsAppDeployRollbackBadRequest{}
}

/*PostAppsAppDeployRollbackBadRequest handles this case with default header values.

Invalid data
*/
type PostAppsAppDeployRollbackBadRequest struct {
}

func (o *PostAppsAppDeployRollbackBadRequest) Error() string {
	return fmt.Sprintf("[POST /apps/{app}/deploy/rollback][%d] postAppsAppDeployRollbackBadRequest ", 400)
}

func (o *PostAppsAppDeployRollbackBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPostAppsAppDeployRollbackForbidden creates a PostAppsAppDeployRollbackForbidden with default headers values
func NewPostAppsAppDeployRollbackForbidden() *PostAppsAppDeployRollbackForbidden {
	return &PostAppsAppDeployRollbackForbidden{}
}

/*PostAppsAppDeployRollbackForbidden handles this case with default header values.

Forbidden
*/
type PostAppsAppDeployRollbackForbidden struct {
}

func (o *PostAppsAppDeployRollbackForbidden) Error() string {
	return fmt.Sprintf("[POST /apps/{app}/deploy/rollback][%d] postAppsAppDeployRollbackForbidden ", 403)
}

func (o *PostAppsAppDeployRollbackForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPostAppsAppDeployRollbackNotFound creates a PostAppsAppDeployRollbackNotFound with default headers values
func NewPostAppsAppDeployRollbackNotFound() *PostAppsAppDeployRollbackNotFound {
	return &PostAppsAppDeployRollbackNotFound{}
}

/*PostAppsAppDeployRollbackNotFound handles this case with default header values.

Not found
*/
type PostAppsAppDeployRollbackNotFound struct {
}

func (o *PostAppsAppDeployRollbackNotFound) Error() string {
	return fmt.Sprintf("[POST /apps/{app}/deploy/rollback][%d] postAppsAppDeployRollbackNotFound ", 404)
}

func (o *PostAppsAppDeployRollbackNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
