// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// PostAppsAppRunReader is a Reader for the PostAppsAppRun structure.
type PostAppsAppRunReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostAppsAppRunReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewPostAppsAppRunOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 401:
		result := NewPostAppsAppRunUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 404:
		result := NewPostAppsAppRunNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPostAppsAppRunOK creates a PostAppsAppRunOK with default headers values
func NewPostAppsAppRunOK() *PostAppsAppRunOK {
	return &PostAppsAppRunOK{}
}

/*PostAppsAppRunOK handles this case with default header values.

Ok
*/
type PostAppsAppRunOK struct {
}

func (o *PostAppsAppRunOK) Error() string {
	return fmt.Sprintf("[POST /apps/{app}/run][%d] postAppsAppRunOK ", 200)
}

func (o *PostAppsAppRunOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPostAppsAppRunUnauthorized creates a PostAppsAppRunUnauthorized with default headers values
func NewPostAppsAppRunUnauthorized() *PostAppsAppRunUnauthorized {
	return &PostAppsAppRunUnauthorized{}
}

/*PostAppsAppRunUnauthorized handles this case with default header values.

Unauthorized
*/
type PostAppsAppRunUnauthorized struct {
}

func (o *PostAppsAppRunUnauthorized) Error() string {
	return fmt.Sprintf("[POST /apps/{app}/run][%d] postAppsAppRunUnauthorized ", 401)
}

func (o *PostAppsAppRunUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPostAppsAppRunNotFound creates a PostAppsAppRunNotFound with default headers values
func NewPostAppsAppRunNotFound() *PostAppsAppRunNotFound {
	return &PostAppsAppRunNotFound{}
}

/*PostAppsAppRunNotFound handles this case with default header values.

App not found
*/
type PostAppsAppRunNotFound struct {
}

func (o *PostAppsAppRunNotFound) Error() string {
	return fmt.Sprintf("[POST /apps/{app}/run][%d] postAppsAppRunNotFound ", 404)
}

func (o *PostAppsAppRunNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
