// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewPostUsersKeysParams creates a new PostUsersKeysParams object
// with the default values initialized.
func NewPostUsersKeysParams() *PostUsersKeysParams {

	return &PostUsersKeysParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPostUsersKeysParamsWithTimeout creates a new PostUsersKeysParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPostUsersKeysParamsWithTimeout(timeout time.Duration) *PostUsersKeysParams {

	return &PostUsersKeysParams{

		timeout: timeout,
	}
}

// NewPostUsersKeysParamsWithContext creates a new PostUsersKeysParams object
// with the default values initialized, and the ability to set a context for a request
func NewPostUsersKeysParamsWithContext(ctx context.Context) *PostUsersKeysParams {

	return &PostUsersKeysParams{

		Context: ctx,
	}
}

// NewPostUsersKeysParamsWithHTTPClient creates a new PostUsersKeysParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPostUsersKeysParamsWithHTTPClient(client *http.Client) *PostUsersKeysParams {

	return &PostUsersKeysParams{
		HTTPClient: client,
	}
}

/*PostUsersKeysParams contains all the parameters to send to the API endpoint
for the post users keys operation typically these are written to a http.Request
*/
type PostUsersKeysParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the post users keys params
func (o *PostUsersKeysParams) WithTimeout(timeout time.Duration) *PostUsersKeysParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post users keys params
func (o *PostUsersKeysParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post users keys params
func (o *PostUsersKeysParams) WithContext(ctx context.Context) *PostUsersKeysParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post users keys params
func (o *PostUsersKeysParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post users keys params
func (o *PostUsersKeysParams) WithHTTPClient(client *http.Client) *PostUsersKeysParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post users keys params
func (o *PostUsersKeysParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *PostUsersKeysParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
