// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewPostAppsAppDeployRollbackParams creates a new PostAppsAppDeployRollbackParams object
// with the default values initialized.
func NewPostAppsAppDeployRollbackParams() *PostAppsAppDeployRollbackParams {
	var ()
	return &PostAppsAppDeployRollbackParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPostAppsAppDeployRollbackParamsWithTimeout creates a new PostAppsAppDeployRollbackParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPostAppsAppDeployRollbackParamsWithTimeout(timeout time.Duration) *PostAppsAppDeployRollbackParams {
	var ()
	return &PostAppsAppDeployRollbackParams{

		timeout: timeout,
	}
}

// NewPostAppsAppDeployRollbackParamsWithContext creates a new PostAppsAppDeployRollbackParams object
// with the default values initialized, and the ability to set a context for a request
func NewPostAppsAppDeployRollbackParamsWithContext(ctx context.Context) *PostAppsAppDeployRollbackParams {
	var ()
	return &PostAppsAppDeployRollbackParams{

		Context: ctx,
	}
}

// NewPostAppsAppDeployRollbackParamsWithHTTPClient creates a new PostAppsAppDeployRollbackParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPostAppsAppDeployRollbackParamsWithHTTPClient(client *http.Client) *PostAppsAppDeployRollbackParams {
	var ()
	return &PostAppsAppDeployRollbackParams{
		HTTPClient: client,
	}
}

/*PostAppsAppDeployRollbackParams contains all the parameters to send to the API endpoint
for the post apps app deploy rollback operation typically these are written to a http.Request
*/
type PostAppsAppDeployRollbackParams struct {

	/*App
	  App name.

	*/
	App string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the post apps app deploy rollback params
func (o *PostAppsAppDeployRollbackParams) WithTimeout(timeout time.Duration) *PostAppsAppDeployRollbackParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post apps app deploy rollback params
func (o *PostAppsAppDeployRollbackParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post apps app deploy rollback params
func (o *PostAppsAppDeployRollbackParams) WithContext(ctx context.Context) *PostAppsAppDeployRollbackParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post apps app deploy rollback params
func (o *PostAppsAppDeployRollbackParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post apps app deploy rollback params
func (o *PostAppsAppDeployRollbackParams) WithHTTPClient(client *http.Client) *PostAppsAppDeployRollbackParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post apps app deploy rollback params
func (o *PostAppsAppDeployRollbackParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithApp adds the app to the post apps app deploy rollback params
func (o *PostAppsAppDeployRollbackParams) WithApp(app string) *PostAppsAppDeployRollbackParams {
	o.SetApp(app)
	return o
}

// SetApp adds the app to the post apps app deploy rollback params
func (o *PostAppsAppDeployRollbackParams) SetApp(app string) {
	o.App = app
}

// WriteToRequest writes these params to a swagger request
func (o *PostAppsAppDeployRollbackParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param app
	if err := r.SetPathParam("app", o.App); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
