// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// PostRoleDefaultReader is a Reader for the PostRoleDefault structure.
type PostRoleDefaultReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostRoleDefaultReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewPostRoleDefaultOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewPostRoleDefaultBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 401:
		result := NewPostRoleDefaultUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPostRoleDefaultOK creates a PostRoleDefaultOK with default headers values
func NewPostRoleDefaultOK() *PostRoleDefaultOK {
	return &PostRoleDefaultOK{}
}

/*PostRoleDefaultOK handles this case with default header values.

Ok
*/
type PostRoleDefaultOK struct {
}

func (o *PostRoleDefaultOK) Error() string {
	return fmt.Sprintf("[POST /role/default][%d] postRoleDefaultOK ", 200)
}

func (o *PostRoleDefaultOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPostRoleDefaultBadRequest creates a PostRoleDefaultBadRequest with default headers values
func NewPostRoleDefaultBadRequest() *PostRoleDefaultBadRequest {
	return &PostRoleDefaultBadRequest{}
}

/*PostRoleDefaultBadRequest handles this case with default header values.

Invalid data
*/
type PostRoleDefaultBadRequest struct {
}

func (o *PostRoleDefaultBadRequest) Error() string {
	return fmt.Sprintf("[POST /role/default][%d] postRoleDefaultBadRequest ", 400)
}

func (o *PostRoleDefaultBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPostRoleDefaultUnauthorized creates a PostRoleDefaultUnauthorized with default headers values
func NewPostRoleDefaultUnauthorized() *PostRoleDefaultUnauthorized {
	return &PostRoleDefaultUnauthorized{}
}

/*PostRoleDefaultUnauthorized handles this case with default header values.

Unauthorized
*/
type PostRoleDefaultUnauthorized struct {
}

func (o *PostRoleDefaultUnauthorized) Error() string {
	return fmt.Sprintf("[POST /role/default][%d] postRoleDefaultUnauthorized ", 401)
}

func (o *PostRoleDefaultUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
