// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewPostAppsAppSleepParams creates a new PostAppsAppSleepParams object
// with the default values initialized.
func NewPostAppsAppSleepParams() *PostAppsAppSleepParams {
	var ()
	return &PostAppsAppSleepParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPostAppsAppSleepParamsWithTimeout creates a new PostAppsAppSleepParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPostAppsAppSleepParamsWithTimeout(timeout time.Duration) *PostAppsAppSleepParams {
	var ()
	return &PostAppsAppSleepParams{

		timeout: timeout,
	}
}

// NewPostAppsAppSleepParamsWithContext creates a new PostAppsAppSleepParams object
// with the default values initialized, and the ability to set a context for a request
func NewPostAppsAppSleepParamsWithContext(ctx context.Context) *PostAppsAppSleepParams {
	var ()
	return &PostAppsAppSleepParams{

		Context: ctx,
	}
}

// NewPostAppsAppSleepParamsWithHTTPClient creates a new PostAppsAppSleepParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPostAppsAppSleepParamsWithHTTPClient(client *http.Client) *PostAppsAppSleepParams {
	var ()
	return &PostAppsAppSleepParams{
		HTTPClient: client,
	}
}

/*PostAppsAppSleepParams contains all the parameters to send to the API endpoint
for the post apps app sleep operation typically these are written to a http.Request
*/
type PostAppsAppSleepParams struct {

	/*App
	  App name.

	*/
	App string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the post apps app sleep params
func (o *PostAppsAppSleepParams) WithTimeout(timeout time.Duration) *PostAppsAppSleepParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post apps app sleep params
func (o *PostAppsAppSleepParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post apps app sleep params
func (o *PostAppsAppSleepParams) WithContext(ctx context.Context) *PostAppsAppSleepParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post apps app sleep params
func (o *PostAppsAppSleepParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post apps app sleep params
func (o *PostAppsAppSleepParams) WithHTTPClient(client *http.Client) *PostAppsAppSleepParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post apps app sleep params
func (o *PostAppsAppSleepParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithApp adds the app to the post apps app sleep params
func (o *PostAppsAppSleepParams) WithApp(app string) *PostAppsAppSleepParams {
	o.SetApp(app)
	return o
}

// SetApp adds the app to the post apps app sleep params
func (o *PostAppsAppSleepParams) SetApp(app string) {
	o.App = app
}

// WriteToRequest writes these params to a swagger request
func (o *PostAppsAppSleepParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param app
	if err := r.SetPathParam("app", o.App); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
