// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewPostAppsAppRunParams creates a new PostAppsAppRunParams object
// with the default values initialized.
func NewPostAppsAppRunParams() *PostAppsAppRunParams {
	var ()
	return &PostAppsAppRunParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPostAppsAppRunParamsWithTimeout creates a new PostAppsAppRunParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPostAppsAppRunParamsWithTimeout(timeout time.Duration) *PostAppsAppRunParams {
	var ()
	return &PostAppsAppRunParams{

		timeout: timeout,
	}
}

// NewPostAppsAppRunParamsWithContext creates a new PostAppsAppRunParams object
// with the default values initialized, and the ability to set a context for a request
func NewPostAppsAppRunParamsWithContext(ctx context.Context) *PostAppsAppRunParams {
	var ()
	return &PostAppsAppRunParams{

		Context: ctx,
	}
}

// NewPostAppsAppRunParamsWithHTTPClient creates a new PostAppsAppRunParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPostAppsAppRunParamsWithHTTPClient(client *http.Client) *PostAppsAppRunParams {
	var ()
	return &PostAppsAppRunParams{
		HTTPClient: client,
	}
}

/*PostAppsAppRunParams contains all the parameters to send to the API endpoint
for the post apps app run operation typically these are written to a http.Request
*/
type PostAppsAppRunParams struct {

	/*App
	  App name.

	*/
	App string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the post apps app run params
func (o *PostAppsAppRunParams) WithTimeout(timeout time.Duration) *PostAppsAppRunParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post apps app run params
func (o *PostAppsAppRunParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post apps app run params
func (o *PostAppsAppRunParams) WithContext(ctx context.Context) *PostAppsAppRunParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post apps app run params
func (o *PostAppsAppRunParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post apps app run params
func (o *PostAppsAppRunParams) WithHTTPClient(client *http.Client) *PostAppsAppRunParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post apps app run params
func (o *PostAppsAppRunParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithApp adds the app to the post apps app run params
func (o *PostAppsAppRunParams) WithApp(app string) *PostAppsAppRunParams {
	o.SetApp(app)
	return o
}

// SetApp adds the app to the post apps app run params
func (o *PostAppsAppRunParams) SetApp(app string) {
	o.App = app
}

// WriteToRequest writes these params to a swagger request
func (o *PostAppsAppRunParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param app
	if err := r.SetPathParam("app", o.App); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
