// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewPostAppsAppDiffParams creates a new PostAppsAppDiffParams object
// with the default values initialized.
func NewPostAppsAppDiffParams() *PostAppsAppDiffParams {
	var ()
	return &PostAppsAppDiffParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPostAppsAppDiffParamsWithTimeout creates a new PostAppsAppDiffParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPostAppsAppDiffParamsWithTimeout(timeout time.Duration) *PostAppsAppDiffParams {
	var ()
	return &PostAppsAppDiffParams{

		timeout: timeout,
	}
}

// NewPostAppsAppDiffParamsWithContext creates a new PostAppsAppDiffParams object
// with the default values initialized, and the ability to set a context for a request
func NewPostAppsAppDiffParamsWithContext(ctx context.Context) *PostAppsAppDiffParams {
	var ()
	return &PostAppsAppDiffParams{

		Context: ctx,
	}
}

// NewPostAppsAppDiffParamsWithHTTPClient creates a new PostAppsAppDiffParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPostAppsAppDiffParamsWithHTTPClient(client *http.Client) *PostAppsAppDiffParams {
	var ()
	return &PostAppsAppDiffParams{
		HTTPClient: client,
	}
}

/*PostAppsAppDiffParams contains all the parameters to send to the API endpoint
for the post apps app diff operation typically these are written to a http.Request
*/
type PostAppsAppDiffParams struct {

	/*App
	  App name.

	*/
	App string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the post apps app diff params
func (o *PostAppsAppDiffParams) WithTimeout(timeout time.Duration) *PostAppsAppDiffParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post apps app diff params
func (o *PostAppsAppDiffParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post apps app diff params
func (o *PostAppsAppDiffParams) WithContext(ctx context.Context) *PostAppsAppDiffParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post apps app diff params
func (o *PostAppsAppDiffParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post apps app diff params
func (o *PostAppsAppDiffParams) WithHTTPClient(client *http.Client) *PostAppsAppDiffParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post apps app diff params
func (o *PostAppsAppDiffParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithApp adds the app to the post apps app diff params
func (o *PostAppsAppDiffParams) WithApp(app string) *PostAppsAppDiffParams {
	o.SetApp(app)
	return o
}

// SetApp adds the app to the post apps app diff params
func (o *PostAppsAppDiffParams) SetApp(app string) {
	o.App = app
}

// WriteToRequest writes these params to a swagger request
func (o *PostAppsAppDiffParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param app
	if err := r.SetPathParam("app", o.App); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
