// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// PostRolesNameUserReader is a Reader for the PostRolesNameUser structure.
type PostRolesNameUserReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostRolesNameUserReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewPostRolesNameUserOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewPostRolesNameUserBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 401:
		result := NewPostRolesNameUserUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 404:
		result := NewPostRolesNameUserNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPostRolesNameUserOK creates a PostRolesNameUserOK with default headers values
func NewPostRolesNameUserOK() *PostRolesNameUserOK {
	return &PostRolesNameUserOK{}
}

/*PostRolesNameUserOK handles this case with default header values.

Ok
*/
type PostRolesNameUserOK struct {
}

func (o *PostRolesNameUserOK) Error() string {
	return fmt.Sprintf("[POST /roles/{name}/user][%d] postRolesNameUserOK ", 200)
}

func (o *PostRolesNameUserOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPostRolesNameUserBadRequest creates a PostRolesNameUserBadRequest with default headers values
func NewPostRolesNameUserBadRequest() *PostRolesNameUserBadRequest {
	return &PostRolesNameUserBadRequest{}
}

/*PostRolesNameUserBadRequest handles this case with default header values.

Invalid data
*/
type PostRolesNameUserBadRequest struct {
}

func (o *PostRolesNameUserBadRequest) Error() string {
	return fmt.Sprintf("[POST /roles/{name}/user][%d] postRolesNameUserBadRequest ", 400)
}

func (o *PostRolesNameUserBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPostRolesNameUserUnauthorized creates a PostRolesNameUserUnauthorized with default headers values
func NewPostRolesNameUserUnauthorized() *PostRolesNameUserUnauthorized {
	return &PostRolesNameUserUnauthorized{}
}

/*PostRolesNameUserUnauthorized handles this case with default header values.

Unauthorized
*/
type PostRolesNameUserUnauthorized struct {
}

func (o *PostRolesNameUserUnauthorized) Error() string {
	return fmt.Sprintf("[POST /roles/{name}/user][%d] postRolesNameUserUnauthorized ", 401)
}

func (o *PostRolesNameUserUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPostRolesNameUserNotFound creates a PostRolesNameUserNotFound with default headers values
func NewPostRolesNameUserNotFound() *PostRolesNameUserNotFound {
	return &PostRolesNameUserNotFound{}
}

/*PostRolesNameUserNotFound handles this case with default header values.

Role not found
*/
type PostRolesNameUserNotFound struct {
}

func (o *PostRolesNameUserNotFound) Error() string {
	return fmt.Sprintf("[POST /roles/{name}/user][%d] postRolesNameUserNotFound ", 404)
}

func (o *PostRolesNameUserNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
