// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// PostTeamsTeamReader is a Reader for the PostTeamsTeam structure.
type PostTeamsTeamReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostTeamsTeamReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewPostTeamsTeamOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewPostTeamsTeamBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 401:
		result := NewPostTeamsTeamUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 404:
		result := NewPostTeamsTeamNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPostTeamsTeamOK creates a PostTeamsTeamOK with default headers values
func NewPostTeamsTeamOK() *PostTeamsTeamOK {
	return &PostTeamsTeamOK{}
}

/*PostTeamsTeamOK handles this case with default header values.

Team updated
*/
type PostTeamsTeamOK struct {
}

func (o *PostTeamsTeamOK) Error() string {
	return fmt.Sprintf("[POST /teams/{team}][%d] postTeamsTeamOK ", 200)
}

func (o *PostTeamsTeamOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPostTeamsTeamBadRequest creates a PostTeamsTeamBadRequest with default headers values
func NewPostTeamsTeamBadRequest() *PostTeamsTeamBadRequest {
	return &PostTeamsTeamBadRequest{}
}

/*PostTeamsTeamBadRequest handles this case with default header values.

Invalid data
*/
type PostTeamsTeamBadRequest struct {
}

func (o *PostTeamsTeamBadRequest) Error() string {
	return fmt.Sprintf("[POST /teams/{team}][%d] postTeamsTeamBadRequest ", 400)
}

func (o *PostTeamsTeamBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPostTeamsTeamUnauthorized creates a PostTeamsTeamUnauthorized with default headers values
func NewPostTeamsTeamUnauthorized() *PostTeamsTeamUnauthorized {
	return &PostTeamsTeamUnauthorized{}
}

/*PostTeamsTeamUnauthorized handles this case with default header values.

Unauthorized
*/
type PostTeamsTeamUnauthorized struct {
}

func (o *PostTeamsTeamUnauthorized) Error() string {
	return fmt.Sprintf("[POST /teams/{team}][%d] postTeamsTeamUnauthorized ", 401)
}

func (o *PostTeamsTeamUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPostTeamsTeamNotFound creates a PostTeamsTeamNotFound with default headers values
func NewPostTeamsTeamNotFound() *PostTeamsTeamNotFound {
	return &PostTeamsTeamNotFound{}
}

/*PostTeamsTeamNotFound handles this case with default header values.

Team not found
*/
type PostTeamsTeamNotFound struct {
}

func (o *PostTeamsTeamNotFound) Error() string {
	return fmt.Sprintf("[POST /teams/{team}][%d] postTeamsTeamNotFound ", 404)
}

func (o *PostTeamsTeamNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
