// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewPostTeamsTeamParams creates a new PostTeamsTeamParams object
// with the default values initialized.
func NewPostTeamsTeamParams() *PostTeamsTeamParams {
	var ()
	return &PostTeamsTeamParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPostTeamsTeamParamsWithTimeout creates a new PostTeamsTeamParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPostTeamsTeamParamsWithTimeout(timeout time.Duration) *PostTeamsTeamParams {
	var ()
	return &PostTeamsTeamParams{

		timeout: timeout,
	}
}

// NewPostTeamsTeamParamsWithContext creates a new PostTeamsTeamParams object
// with the default values initialized, and the ability to set a context for a request
func NewPostTeamsTeamParamsWithContext(ctx context.Context) *PostTeamsTeamParams {
	var ()
	return &PostTeamsTeamParams{

		Context: ctx,
	}
}

// NewPostTeamsTeamParamsWithHTTPClient creates a new PostTeamsTeamParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPostTeamsTeamParamsWithHTTPClient(client *http.Client) *PostTeamsTeamParams {
	var ()
	return &PostTeamsTeamParams{
		HTTPClient: client,
	}
}

/*PostTeamsTeamParams contains all the parameters to send to the API endpoint
for the post teams team operation typically these are written to a http.Request
*/
type PostTeamsTeamParams struct {

	/*Team
	  Team name.

	*/
	Team string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the post teams team params
func (o *PostTeamsTeamParams) WithTimeout(timeout time.Duration) *PostTeamsTeamParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post teams team params
func (o *PostTeamsTeamParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post teams team params
func (o *PostTeamsTeamParams) WithContext(ctx context.Context) *PostTeamsTeamParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post teams team params
func (o *PostTeamsTeamParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post teams team params
func (o *PostTeamsTeamParams) WithHTTPClient(client *http.Client) *PostTeamsTeamParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post teams team params
func (o *PostTeamsTeamParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithTeam adds the team to the post teams team params
func (o *PostTeamsTeamParams) WithTeam(team string) *PostTeamsTeamParams {
	o.SetTeam(team)
	return o
}

// SetTeam adds the team to the post teams team params
func (o *PostTeamsTeamParams) SetTeam(team string) {
	o.Team = team
}

// WriteToRequest writes these params to a swagger request
func (o *PostTeamsTeamParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param team
	if err := r.SetPathParam("team", o.Team); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
