// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewPostAppsAppStartParams creates a new PostAppsAppStartParams object
// with the default values initialized.
func NewPostAppsAppStartParams() *PostAppsAppStartParams {
	var ()
	return &PostAppsAppStartParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPostAppsAppStartParamsWithTimeout creates a new PostAppsAppStartParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPostAppsAppStartParamsWithTimeout(timeout time.Duration) *PostAppsAppStartParams {
	var ()
	return &PostAppsAppStartParams{

		timeout: timeout,
	}
}

// NewPostAppsAppStartParamsWithContext creates a new PostAppsAppStartParams object
// with the default values initialized, and the ability to set a context for a request
func NewPostAppsAppStartParamsWithContext(ctx context.Context) *PostAppsAppStartParams {
	var ()
	return &PostAppsAppStartParams{

		Context: ctx,
	}
}

// NewPostAppsAppStartParamsWithHTTPClient creates a new PostAppsAppStartParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPostAppsAppStartParamsWithHTTPClient(client *http.Client) *PostAppsAppStartParams {
	var ()
	return &PostAppsAppStartParams{
		HTTPClient: client,
	}
}

/*PostAppsAppStartParams contains all the parameters to send to the API endpoint
for the post apps app start operation typically these are written to a http.Request
*/
type PostAppsAppStartParams struct {

	/*App
	  App name.

	*/
	App string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the post apps app start params
func (o *PostAppsAppStartParams) WithTimeout(timeout time.Duration) *PostAppsAppStartParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post apps app start params
func (o *PostAppsAppStartParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post apps app start params
func (o *PostAppsAppStartParams) WithContext(ctx context.Context) *PostAppsAppStartParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post apps app start params
func (o *PostAppsAppStartParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post apps app start params
func (o *PostAppsAppStartParams) WithHTTPClient(client *http.Client) *PostAppsAppStartParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post apps app start params
func (o *PostAppsAppStartParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithApp adds the app to the post apps app start params
func (o *PostAppsAppStartParams) WithApp(app string) *PostAppsAppStartParams {
	o.SetApp(app)
	return o
}

// SetApp adds the app to the post apps app start params
func (o *PostAppsAppStartParams) SetApp(app string) {
	o.App = app
}

// WriteToRequest writes these params to a swagger request
func (o *PostAppsAppStartParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param app
	if err := r.SetPathParam("app", o.App); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
