// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewPostAutoscaleRunParams creates a new PostAutoscaleRunParams object
// with the default values initialized.
func NewPostAutoscaleRunParams() *PostAutoscaleRunParams {

	return &PostAutoscaleRunParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPostAutoscaleRunParamsWithTimeout creates a new PostAutoscaleRunParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPostAutoscaleRunParamsWithTimeout(timeout time.Duration) *PostAutoscaleRunParams {

	return &PostAutoscaleRunParams{

		timeout: timeout,
	}
}

// NewPostAutoscaleRunParamsWithContext creates a new PostAutoscaleRunParams object
// with the default values initialized, and the ability to set a context for a request
func NewPostAutoscaleRunParamsWithContext(ctx context.Context) *PostAutoscaleRunParams {

	return &PostAutoscaleRunParams{

		Context: ctx,
	}
}

// NewPostAutoscaleRunParamsWithHTTPClient creates a new PostAutoscaleRunParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPostAutoscaleRunParamsWithHTTPClient(client *http.Client) *PostAutoscaleRunParams {

	return &PostAutoscaleRunParams{
		HTTPClient: client,
	}
}

/*PostAutoscaleRunParams contains all the parameters to send to the API endpoint
for the post autoscale run operation typically these are written to a http.Request
*/
type PostAutoscaleRunParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the post autoscale run params
func (o *PostAutoscaleRunParams) WithTimeout(timeout time.Duration) *PostAutoscaleRunParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post autoscale run params
func (o *PostAutoscaleRunParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post autoscale run params
func (o *PostAutoscaleRunParams) WithContext(ctx context.Context) *PostAutoscaleRunParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post autoscale run params
func (o *PostAutoscaleRunParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post autoscale run params
func (o *PostAutoscaleRunParams) WithHTTPClient(client *http.Client) *PostAutoscaleRunParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post autoscale run params
func (o *PostAutoscaleRunParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *PostAutoscaleRunParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
