// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewPostUsersEmailPasswordParams creates a new PostUsersEmailPasswordParams object
// with the default values initialized.
func NewPostUsersEmailPasswordParams() *PostUsersEmailPasswordParams {
	var ()
	return &PostUsersEmailPasswordParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPostUsersEmailPasswordParamsWithTimeout creates a new PostUsersEmailPasswordParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPostUsersEmailPasswordParamsWithTimeout(timeout time.Duration) *PostUsersEmailPasswordParams {
	var ()
	return &PostUsersEmailPasswordParams{

		timeout: timeout,
	}
}

// NewPostUsersEmailPasswordParamsWithContext creates a new PostUsersEmailPasswordParams object
// with the default values initialized, and the ability to set a context for a request
func NewPostUsersEmailPasswordParamsWithContext(ctx context.Context) *PostUsersEmailPasswordParams {
	var ()
	return &PostUsersEmailPasswordParams{

		Context: ctx,
	}
}

// NewPostUsersEmailPasswordParamsWithHTTPClient creates a new PostUsersEmailPasswordParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPostUsersEmailPasswordParamsWithHTTPClient(client *http.Client) *PostUsersEmailPasswordParams {
	var ()
	return &PostUsersEmailPasswordParams{
		HTTPClient: client,
	}
}

/*PostUsersEmailPasswordParams contains all the parameters to send to the API endpoint
for the post users email password operation typically these are written to a http.Request
*/
type PostUsersEmailPasswordParams struct {

	/*Email
	  User e-mail.

	*/
	Email string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the post users email password params
func (o *PostUsersEmailPasswordParams) WithTimeout(timeout time.Duration) *PostUsersEmailPasswordParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post users email password params
func (o *PostUsersEmailPasswordParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post users email password params
func (o *PostUsersEmailPasswordParams) WithContext(ctx context.Context) *PostUsersEmailPasswordParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post users email password params
func (o *PostUsersEmailPasswordParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post users email password params
func (o *PostUsersEmailPasswordParams) WithHTTPClient(client *http.Client) *PostUsersEmailPasswordParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post users email password params
func (o *PostUsersEmailPasswordParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithEmail adds the email to the post users email password params
func (o *PostUsersEmailPasswordParams) WithEmail(email string) *PostUsersEmailPasswordParams {
	o.SetEmail(email)
	return o
}

// SetEmail adds the email to the post users email password params
func (o *PostUsersEmailPasswordParams) SetEmail(email string) {
	o.Email = email
}

// WriteToRequest writes these params to a swagger request
func (o *PostUsersEmailPasswordParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param email
	if err := r.SetPathParam("email", o.Email); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
