// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// PutNodeReader is a Reader for the PutNode structure.
type PutNodeReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PutNodeReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewPutNodeOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewPutNodeBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 401:
		result := NewPutNodeUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 404:
		result := NewPutNodeNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPutNodeOK creates a PutNodeOK with default headers values
func NewPutNodeOK() *PutNodeOK {
	return &PutNodeOK{}
}

/*PutNodeOK handles this case with default header values.

Ok
*/
type PutNodeOK struct {
}

func (o *PutNodeOK) Error() string {
	return fmt.Sprintf("[PUT /node][%d] putNodeOK ", 200)
}

func (o *PutNodeOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPutNodeBadRequest creates a PutNodeBadRequest with default headers values
func NewPutNodeBadRequest() *PutNodeBadRequest {
	return &PutNodeBadRequest{}
}

/*PutNodeBadRequest handles this case with default header values.

Invalid data
*/
type PutNodeBadRequest struct {
}

func (o *PutNodeBadRequest) Error() string {
	return fmt.Sprintf("[PUT /node][%d] putNodeBadRequest ", 400)
}

func (o *PutNodeBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPutNodeUnauthorized creates a PutNodeUnauthorized with default headers values
func NewPutNodeUnauthorized() *PutNodeUnauthorized {
	return &PutNodeUnauthorized{}
}

/*PutNodeUnauthorized handles this case with default header values.

Unauthorized
*/
type PutNodeUnauthorized struct {
}

func (o *PutNodeUnauthorized) Error() string {
	return fmt.Sprintf("[PUT /node][%d] putNodeUnauthorized ", 401)
}

func (o *PutNodeUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPutNodeNotFound creates a PutNodeNotFound with default headers values
func NewPutNodeNotFound() *PutNodeNotFound {
	return &PutNodeNotFound{}
}

/*PutNodeNotFound handles this case with default header values.

Not found
*/
type PutNodeNotFound struct {
}

func (o *PutNodeNotFound) Error() string {
	return fmt.Sprintf("[PUT /node][%d] putNodeNotFound ", 404)
}

func (o *PutNodeNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
