// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewPutAppAppRoutersRouterParams creates a new PutAppAppRoutersRouterParams object
// with the default values initialized.
func NewPutAppAppRoutersRouterParams() *PutAppAppRoutersRouterParams {
	var ()
	return &PutAppAppRoutersRouterParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPutAppAppRoutersRouterParamsWithTimeout creates a new PutAppAppRoutersRouterParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPutAppAppRoutersRouterParamsWithTimeout(timeout time.Duration) *PutAppAppRoutersRouterParams {
	var ()
	return &PutAppAppRoutersRouterParams{

		timeout: timeout,
	}
}

// NewPutAppAppRoutersRouterParamsWithContext creates a new PutAppAppRoutersRouterParams object
// with the default values initialized, and the ability to set a context for a request
func NewPutAppAppRoutersRouterParamsWithContext(ctx context.Context) *PutAppAppRoutersRouterParams {
	var ()
	return &PutAppAppRoutersRouterParams{

		Context: ctx,
	}
}

// NewPutAppAppRoutersRouterParamsWithHTTPClient creates a new PutAppAppRoutersRouterParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPutAppAppRoutersRouterParamsWithHTTPClient(client *http.Client) *PutAppAppRoutersRouterParams {
	var ()
	return &PutAppAppRoutersRouterParams{
		HTTPClient: client,
	}
}

/*PutAppAppRoutersRouterParams contains all the parameters to send to the API endpoint
for the put app app routers router operation typically these are written to a http.Request
*/
type PutAppAppRoutersRouterParams struct {

	/*App
	  App name.

	*/
	App string
	/*Router
	  Router name.

	*/
	Router string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the put app app routers router params
func (o *PutAppAppRoutersRouterParams) WithTimeout(timeout time.Duration) *PutAppAppRoutersRouterParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the put app app routers router params
func (o *PutAppAppRoutersRouterParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the put app app routers router params
func (o *PutAppAppRoutersRouterParams) WithContext(ctx context.Context) *PutAppAppRoutersRouterParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the put app app routers router params
func (o *PutAppAppRoutersRouterParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the put app app routers router params
func (o *PutAppAppRoutersRouterParams) WithHTTPClient(client *http.Client) *PutAppAppRoutersRouterParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the put app app routers router params
func (o *PutAppAppRoutersRouterParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithApp adds the app to the put app app routers router params
func (o *PutAppAppRoutersRouterParams) WithApp(app string) *PutAppAppRoutersRouterParams {
	o.SetApp(app)
	return o
}

// SetApp adds the app to the put app app routers router params
func (o *PutAppAppRoutersRouterParams) SetApp(app string) {
	o.App = app
}

// WithRouter adds the router to the put app app routers router params
func (o *PutAppAppRoutersRouterParams) WithRouter(router string) *PutAppAppRoutersRouterParams {
	o.SetRouter(router)
	return o
}

// SetRouter adds the router to the put app app routers router params
func (o *PutAppAppRoutersRouterParams) SetRouter(router string) {
	o.Router = router
}

// WriteToRequest writes these params to a swagger request
func (o *PutAppAppRoutersRouterParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param app
	if err := r.SetPathParam("app", o.App); err != nil {
		return err
	}

	// path param router
	if err := r.SetPathParam("router", o.Router); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
