// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// PutAppAppRoutersRouterReader is a Reader for the PutAppAppRoutersRouter structure.
type PutAppAppRoutersRouterReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PutAppAppRoutersRouterReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewPutAppAppRoutersRouterOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewPutAppAppRoutersRouterBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 404:
		result := NewPutAppAppRoutersRouterNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPutAppAppRoutersRouterOK creates a PutAppAppRoutersRouterOK with default headers values
func NewPutAppAppRoutersRouterOK() *PutAppAppRoutersRouterOK {
	return &PutAppAppRoutersRouterOK{}
}

/*PutAppAppRoutersRouterOK handles this case with default header values.

OK
*/
type PutAppAppRoutersRouterOK struct {
}

func (o *PutAppAppRoutersRouterOK) Error() string {
	return fmt.Sprintf("[PUT /app/{app}/routers/{router}][%d] putAppAppRoutersRouterOK ", 200)
}

func (o *PutAppAppRoutersRouterOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPutAppAppRoutersRouterBadRequest creates a PutAppAppRoutersRouterBadRequest with default headers values
func NewPutAppAppRoutersRouterBadRequest() *PutAppAppRoutersRouterBadRequest {
	return &PutAppAppRoutersRouterBadRequest{}
}

/*PutAppAppRoutersRouterBadRequest handles this case with default header values.

Invalid request
*/
type PutAppAppRoutersRouterBadRequest struct {
}

func (o *PutAppAppRoutersRouterBadRequest) Error() string {
	return fmt.Sprintf("[PUT /app/{app}/routers/{router}][%d] putAppAppRoutersRouterBadRequest ", 400)
}

func (o *PutAppAppRoutersRouterBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPutAppAppRoutersRouterNotFound creates a PutAppAppRoutersRouterNotFound with default headers values
func NewPutAppAppRoutersRouterNotFound() *PutAppAppRoutersRouterNotFound {
	return &PutAppAppRoutersRouterNotFound{}
}

/*PutAppAppRoutersRouterNotFound handles this case with default header values.

App or router not found
*/
type PutAppAppRoutersRouterNotFound struct {
}

func (o *PutAppAppRoutersRouterNotFound) Error() string {
	return fmt.Sprintf("[PUT /app/{app}/routers/{router}][%d] putAppAppRoutersRouterNotFound ", 404)
}

func (o *PutAppAppRoutersRouterNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
