// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewPutIaasTemplatesTemplateParams creates a new PutIaasTemplatesTemplateParams object
// with the default values initialized.
func NewPutIaasTemplatesTemplateParams() *PutIaasTemplatesTemplateParams {
	var ()
	return &PutIaasTemplatesTemplateParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPutIaasTemplatesTemplateParamsWithTimeout creates a new PutIaasTemplatesTemplateParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPutIaasTemplatesTemplateParamsWithTimeout(timeout time.Duration) *PutIaasTemplatesTemplateParams {
	var ()
	return &PutIaasTemplatesTemplateParams{

		timeout: timeout,
	}
}

// NewPutIaasTemplatesTemplateParamsWithContext creates a new PutIaasTemplatesTemplateParams object
// with the default values initialized, and the ability to set a context for a request
func NewPutIaasTemplatesTemplateParamsWithContext(ctx context.Context) *PutIaasTemplatesTemplateParams {
	var ()
	return &PutIaasTemplatesTemplateParams{

		Context: ctx,
	}
}

// NewPutIaasTemplatesTemplateParamsWithHTTPClient creates a new PutIaasTemplatesTemplateParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPutIaasTemplatesTemplateParamsWithHTTPClient(client *http.Client) *PutIaasTemplatesTemplateParams {
	var ()
	return &PutIaasTemplatesTemplateParams{
		HTTPClient: client,
	}
}

/*PutIaasTemplatesTemplateParams contains all the parameters to send to the API endpoint
for the put iaas templates template operation typically these are written to a http.Request
*/
type PutIaasTemplatesTemplateParams struct {

	/*Template
	  Template name.

	*/
	Template string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the put iaas templates template params
func (o *PutIaasTemplatesTemplateParams) WithTimeout(timeout time.Duration) *PutIaasTemplatesTemplateParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the put iaas templates template params
func (o *PutIaasTemplatesTemplateParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the put iaas templates template params
func (o *PutIaasTemplatesTemplateParams) WithContext(ctx context.Context) *PutIaasTemplatesTemplateParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the put iaas templates template params
func (o *PutIaasTemplatesTemplateParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the put iaas templates template params
func (o *PutIaasTemplatesTemplateParams) WithHTTPClient(client *http.Client) *PutIaasTemplatesTemplateParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the put iaas templates template params
func (o *PutIaasTemplatesTemplateParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithTemplate adds the template to the put iaas templates template params
func (o *PutIaasTemplatesTemplateParams) WithTemplate(template string) *PutIaasTemplatesTemplateParams {
	o.SetTemplate(template)
	return o
}

// SetTemplate adds the template to the put iaas templates template params
func (o *PutIaasTemplatesTemplateParams) SetTemplate(template string) {
	o.Template = template
}

// WriteToRequest writes these params to a swagger request
func (o *PutIaasTemplatesTemplateParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param template
	if err := r.SetPathParam("template", o.Template); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
