// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewPutRolesParams creates a new PutRolesParams object
// with the default values initialized.
func NewPutRolesParams() *PutRolesParams {

	return &PutRolesParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPutRolesParamsWithTimeout creates a new PutRolesParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPutRolesParamsWithTimeout(timeout time.Duration) *PutRolesParams {

	return &PutRolesParams{

		timeout: timeout,
	}
}

// NewPutRolesParamsWithContext creates a new PutRolesParams object
// with the default values initialized, and the ability to set a context for a request
func NewPutRolesParamsWithContext(ctx context.Context) *PutRolesParams {

	return &PutRolesParams{

		Context: ctx,
	}
}

// NewPutRolesParamsWithHTTPClient creates a new PutRolesParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPutRolesParamsWithHTTPClient(client *http.Client) *PutRolesParams {

	return &PutRolesParams{
		HTTPClient: client,
	}
}

/*PutRolesParams contains all the parameters to send to the API endpoint
for the put roles operation typically these are written to a http.Request
*/
type PutRolesParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the put roles params
func (o *PutRolesParams) WithTimeout(timeout time.Duration) *PutRolesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the put roles params
func (o *PutRolesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the put roles params
func (o *PutRolesParams) WithContext(ctx context.Context) *PutRolesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the put roles params
func (o *PutRolesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the put roles params
func (o *PutRolesParams) WithHTTPClient(client *http.Client) *PutRolesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the put roles params
func (o *PutRolesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *PutRolesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
