// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewPutAppsAppnameDeployRollbackUpdateParams creates a new PutAppsAppnameDeployRollbackUpdateParams object
// with the default values initialized.
func NewPutAppsAppnameDeployRollbackUpdateParams() *PutAppsAppnameDeployRollbackUpdateParams {

	return &PutAppsAppnameDeployRollbackUpdateParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPutAppsAppnameDeployRollbackUpdateParamsWithTimeout creates a new PutAppsAppnameDeployRollbackUpdateParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPutAppsAppnameDeployRollbackUpdateParamsWithTimeout(timeout time.Duration) *PutAppsAppnameDeployRollbackUpdateParams {

	return &PutAppsAppnameDeployRollbackUpdateParams{

		timeout: timeout,
	}
}

// NewPutAppsAppnameDeployRollbackUpdateParamsWithContext creates a new PutAppsAppnameDeployRollbackUpdateParams object
// with the default values initialized, and the ability to set a context for a request
func NewPutAppsAppnameDeployRollbackUpdateParamsWithContext(ctx context.Context) *PutAppsAppnameDeployRollbackUpdateParams {

	return &PutAppsAppnameDeployRollbackUpdateParams{

		Context: ctx,
	}
}

// NewPutAppsAppnameDeployRollbackUpdateParamsWithHTTPClient creates a new PutAppsAppnameDeployRollbackUpdateParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPutAppsAppnameDeployRollbackUpdateParamsWithHTTPClient(client *http.Client) *PutAppsAppnameDeployRollbackUpdateParams {

	return &PutAppsAppnameDeployRollbackUpdateParams{
		HTTPClient: client,
	}
}

/*PutAppsAppnameDeployRollbackUpdateParams contains all the parameters to send to the API endpoint
for the put apps appname deploy rollback update operation typically these are written to a http.Request
*/
type PutAppsAppnameDeployRollbackUpdateParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the put apps appname deploy rollback update params
func (o *PutAppsAppnameDeployRollbackUpdateParams) WithTimeout(timeout time.Duration) *PutAppsAppnameDeployRollbackUpdateParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the put apps appname deploy rollback update params
func (o *PutAppsAppnameDeployRollbackUpdateParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the put apps appname deploy rollback update params
func (o *PutAppsAppnameDeployRollbackUpdateParams) WithContext(ctx context.Context) *PutAppsAppnameDeployRollbackUpdateParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the put apps appname deploy rollback update params
func (o *PutAppsAppnameDeployRollbackUpdateParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the put apps appname deploy rollback update params
func (o *PutAppsAppnameDeployRollbackUpdateParams) WithHTTPClient(client *http.Client) *PutAppsAppnameDeployRollbackUpdateParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the put apps appname deploy rollback update params
func (o *PutAppsAppnameDeployRollbackUpdateParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *PutAppsAppnameDeployRollbackUpdateParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
