// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewPutAppsAppParams creates a new PutAppsAppParams object
// with the default values initialized.
func NewPutAppsAppParams() *PutAppsAppParams {
	var ()
	return &PutAppsAppParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPutAppsAppParamsWithTimeout creates a new PutAppsAppParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPutAppsAppParamsWithTimeout(timeout time.Duration) *PutAppsAppParams {
	var ()
	return &PutAppsAppParams{

		timeout: timeout,
	}
}

// NewPutAppsAppParamsWithContext creates a new PutAppsAppParams object
// with the default values initialized, and the ability to set a context for a request
func NewPutAppsAppParamsWithContext(ctx context.Context) *PutAppsAppParams {
	var ()
	return &PutAppsAppParams{

		Context: ctx,
	}
}

// NewPutAppsAppParamsWithHTTPClient creates a new PutAppsAppParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPutAppsAppParamsWithHTTPClient(client *http.Client) *PutAppsAppParams {
	var ()
	return &PutAppsAppParams{
		HTTPClient: client,
	}
}

/*PutAppsAppParams contains all the parameters to send to the API endpoint
for the put apps app operation typically these are written to a http.Request
*/
type PutAppsAppParams struct {

	/*App
	  App name.

	*/
	App string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the put apps app params
func (o *PutAppsAppParams) WithTimeout(timeout time.Duration) *PutAppsAppParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the put apps app params
func (o *PutAppsAppParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the put apps app params
func (o *PutAppsAppParams) WithContext(ctx context.Context) *PutAppsAppParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the put apps app params
func (o *PutAppsAppParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the put apps app params
func (o *PutAppsAppParams) WithHTTPClient(client *http.Client) *PutAppsAppParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the put apps app params
func (o *PutAppsAppParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithApp adds the app to the put apps app params
func (o *PutAppsAppParams) WithApp(app string) *PutAppsAppParams {
	o.SetApp(app)
	return o
}

// SetApp adds the app to the put apps app params
func (o *PutAppsAppParams) SetApp(app string) {
	o.App = app
}

// WriteToRequest writes these params to a swagger request
func (o *PutAppsAppParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param app
	if err := r.SetPathParam("app", o.App); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
