// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewPutServicesServiceInstancesInstanceAppParams creates a new PutServicesServiceInstancesInstanceAppParams object
// with the default values initialized.
func NewPutServicesServiceInstancesInstanceAppParams() *PutServicesServiceInstancesInstanceAppParams {
	var ()
	return &PutServicesServiceInstancesInstanceAppParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPutServicesServiceInstancesInstanceAppParamsWithTimeout creates a new PutServicesServiceInstancesInstanceAppParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPutServicesServiceInstancesInstanceAppParamsWithTimeout(timeout time.Duration) *PutServicesServiceInstancesInstanceAppParams {
	var ()
	return &PutServicesServiceInstancesInstanceAppParams{

		timeout: timeout,
	}
}

// NewPutServicesServiceInstancesInstanceAppParamsWithContext creates a new PutServicesServiceInstancesInstanceAppParams object
// with the default values initialized, and the ability to set a context for a request
func NewPutServicesServiceInstancesInstanceAppParamsWithContext(ctx context.Context) *PutServicesServiceInstancesInstanceAppParams {
	var ()
	return &PutServicesServiceInstancesInstanceAppParams{

		Context: ctx,
	}
}

// NewPutServicesServiceInstancesInstanceAppParamsWithHTTPClient creates a new PutServicesServiceInstancesInstanceAppParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPutServicesServiceInstancesInstanceAppParamsWithHTTPClient(client *http.Client) *PutServicesServiceInstancesInstanceAppParams {
	var ()
	return &PutServicesServiceInstancesInstanceAppParams{
		HTTPClient: client,
	}
}

/*PutServicesServiceInstancesInstanceAppParams contains all the parameters to send to the API endpoint
for the put services service instances instance app operation typically these are written to a http.Request
*/
type PutServicesServiceInstancesInstanceAppParams struct {

	/*App
	  App name.

	*/
	App string
	/*Instance
	  Instance name.

	*/
	Instance string
	/*Service
	  Service name.

	*/
	Service string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the put services service instances instance app params
func (o *PutServicesServiceInstancesInstanceAppParams) WithTimeout(timeout time.Duration) *PutServicesServiceInstancesInstanceAppParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the put services service instances instance app params
func (o *PutServicesServiceInstancesInstanceAppParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the put services service instances instance app params
func (o *PutServicesServiceInstancesInstanceAppParams) WithContext(ctx context.Context) *PutServicesServiceInstancesInstanceAppParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the put services service instances instance app params
func (o *PutServicesServiceInstancesInstanceAppParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the put services service instances instance app params
func (o *PutServicesServiceInstancesInstanceAppParams) WithHTTPClient(client *http.Client) *PutServicesServiceInstancesInstanceAppParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the put services service instances instance app params
func (o *PutServicesServiceInstancesInstanceAppParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithApp adds the app to the put services service instances instance app params
func (o *PutServicesServiceInstancesInstanceAppParams) WithApp(app string) *PutServicesServiceInstancesInstanceAppParams {
	o.SetApp(app)
	return o
}

// SetApp adds the app to the put services service instances instance app params
func (o *PutServicesServiceInstancesInstanceAppParams) SetApp(app string) {
	o.App = app
}

// WithInstance adds the instance to the put services service instances instance app params
func (o *PutServicesServiceInstancesInstanceAppParams) WithInstance(instance string) *PutServicesServiceInstancesInstanceAppParams {
	o.SetInstance(instance)
	return o
}

// SetInstance adds the instance to the put services service instances instance app params
func (o *PutServicesServiceInstancesInstanceAppParams) SetInstance(instance string) {
	o.Instance = instance
}

// WithService adds the service to the put services service instances instance app params
func (o *PutServicesServiceInstancesInstanceAppParams) WithService(service string) *PutServicesServiceInstancesInstanceAppParams {
	o.SetService(service)
	return o
}

// SetService adds the service to the put services service instances instance app params
func (o *PutServicesServiceInstancesInstanceAppParams) SetService(service string) {
	o.Service = service
}

// WriteToRequest writes these params to a swagger request
func (o *PutServicesServiceInstancesInstanceAppParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param app
	if err := r.SetPathParam("app", o.App); err != nil {
		return err
	}

	// path param instance
	if err := r.SetPathParam("instance", o.Instance); err != nil {
		return err
	}

	// path param service
	if err := r.SetPathParam("service", o.Service); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
