// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewPutAppAppRoutersNameParams creates a new PutAppAppRoutersNameParams object
// with the default values initialized.
func NewPutAppAppRoutersNameParams() *PutAppAppRoutersNameParams {

	return &PutAppAppRoutersNameParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPutAppAppRoutersNameParamsWithTimeout creates a new PutAppAppRoutersNameParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPutAppAppRoutersNameParamsWithTimeout(timeout time.Duration) *PutAppAppRoutersNameParams {

	return &PutAppAppRoutersNameParams{

		timeout: timeout,
	}
}

// NewPutAppAppRoutersNameParamsWithContext creates a new PutAppAppRoutersNameParams object
// with the default values initialized, and the ability to set a context for a request
func NewPutAppAppRoutersNameParamsWithContext(ctx context.Context) *PutAppAppRoutersNameParams {

	return &PutAppAppRoutersNameParams{

		Context: ctx,
	}
}

// NewPutAppAppRoutersNameParamsWithHTTPClient creates a new PutAppAppRoutersNameParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPutAppAppRoutersNameParamsWithHTTPClient(client *http.Client) *PutAppAppRoutersNameParams {

	return &PutAppAppRoutersNameParams{
		HTTPClient: client,
	}
}

/*PutAppAppRoutersNameParams contains all the parameters to send to the API endpoint
for the put app app routers name operation typically these are written to a http.Request
*/
type PutAppAppRoutersNameParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the put app app routers name params
func (o *PutAppAppRoutersNameParams) WithTimeout(timeout time.Duration) *PutAppAppRoutersNameParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the put app app routers name params
func (o *PutAppAppRoutersNameParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the put app app routers name params
func (o *PutAppAppRoutersNameParams) WithContext(ctx context.Context) *PutAppAppRoutersNameParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the put app app routers name params
func (o *PutAppAppRoutersNameParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the put app app routers name params
func (o *PutAppAppRoutersNameParams) WithHTTPClient(client *http.Client) *PutAppAppRoutersNameParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the put app app routers name params
func (o *PutAppAppRoutersNameParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *PutAppAppRoutersNameParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
