#!/bin/bash
set -e

echo "Checking git installation"
if ! dpkg -l | grep git 2>&1 > /dev/null; then
    echo "Not found, installing..."
    sudo apt-get install git -y
fi

echo "Adding \"git\" user"
sudo useradd git -s /bin/bash

# assumes that current user is the one who will run tsuru's server
echo "Adding ${USER} to group \"git\"" # this has to be done, since tsuru's user will write in git's home
sudo usermod ${USER} -G git

echo "Creating git repository dir"
sudo mkdir /mnt/git-repos
sudo chown git:git /mnt/git-repos
sudo chmod g+w /mnt/git-repos

export TSURU_HOST="http://localhost:4000"
