swagger: "2.0"
info:
  title: Tsuru
  description: Open source, extensible and Docker-based Platform as a Service (PaaS)
  version: "1.6.0"
schemes:
  - http
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
paths:
  /apps:
    get:
      description: list apps
      operationId: List
      produces:
      - application/json
      responses:
        '200':
          description: List apps
        '204':
          description: No content
        '401':
          description: Unauthorized
          schema:
            $ref: '#/definitions/ErrorMessage'
      tags: 
        - app
      security:
        - Bearer: []
    post:
      description: create a new app
      parameters:
        - name: app
          required: true
          in: body
          schema: 
            $ref: '#/definitions/App'
      operationId: Create
      produces:
      - application/json
      consumes:
      - application/json
      responses:
        '201': 
          description: App created
          schema:
            $ref: '#/definitions/AppCreateResponse'
        '400': 
          description: Invalid data
          schema:
            $ref: '#/definitions/ErrorMessage'
        '401': 
          description: Unauthorized
          schema:
            $ref: '#/definitions/ErrorMessage'
        '403': 
          description: Quota exceeded
          schema:
            $ref: '#/definitions/ErrorMessage'
        '409': 
          description: App already exists
          schema:
            $ref: '#/definitions/ErrorMessage'
      tags: 
        - app
      security:
        - Bearer: []
definitions:
  ErrorMessage:
    description: Error message
    type: string
  App:
    description: Tsuru app
    type: object
    required:
      - name
    properties:
      name:
        type: string
        description: App name
      tag:
        type: array
        items:
          type: string
        description: App Tags
      router:
        type: string
        description: App router
      routeropts:
        type: object
        additionalProperties:
          type: string
        description: Custom router options
      plan:
        type: string
        description: App plan
      pool:
        type: string
        description: App pool
      platform:
        type: string
        description: App platform
      description:
        type: string
        description: App description
      teamOwner:
        type: string
        description: Team that owns the app
  AppCreateResponse:
    description: Newly created app information
    type: object
    properties:
      status:
        type: string
      repository_url:
        type: string
      ip:
        type: string