// Copyright 2018 tsuru authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

// This file was automatically generated by lister-gen

package v1

// AppListerExpansion allows custom methods to be added to
// AppLister.
type AppListerExpansion interface{}

// AppNamespaceListerExpansion allows custom methods to be added to
// AppNamespaceLister.
type AppNamespaceListerExpansion interface{}
