name: Issue cleanup
on:
  workflow_dispatch:
  schedule:
  - cron: '37 01 5 */2 *'

jobs:
  triage_issues:
    name: Issue triage
    runs-on: ubuntu-latest
    steps:
    - name: Find old issues and mark them stale
      uses: yuiseki/issue-triage-action@v1.2
      with:
        ghToken: ${{ secrets.GITHUB_TOKEN }}
        staleAfter: 30
        closeAfter: 60
        staleLabel: "STALE 📺"
        staleComment: "This issue is %DAYS_OLD% days old, marking as stale! cc: @%AUTHOR%"
        closeComment: "Issue last updated %DAYS_OLD% days ago! Closing down!"
        showLogs: true
        actionSkipLabels: "never-stale"
